/* Generated by Yosys 0.9+3565 (git sha1 474cd02e, gcc 9.3.0-10ubuntu2 -fPIC -Os) */

(* top =  1  *)
(* src = "module_Recirculacion.v:1.1-24.10" *)
module module_Recirculacion_Sint(active, valid_in_Recir, data_in_Recir, valid_out_Recir_Sint, data_out_Recir_Sint, data_out_Retorno_Sint);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  (* src = "module_Recirculacion.v:2.13-2.19" *)
  input active;
  (* src = "module_Recirculacion.v:4.18-4.31" *)
  input [31:0] data_in_Recir;
  (* src = "module_Recirculacion.v:6.23-6.37" *)
  output [31:0] data_out_Recir_Sint;
  (* src = "module_Recirculacion.v:7.23-7.39" *)
  output [31:0] data_out_Retorno_Sint;
  (* src = "module_Recirculacion.v:3.13-3.27" *)
  input valid_in_Recir;
  (* src = "module_Recirculacion.v:5.17-5.32" *)
  output valid_out_Recir_Sint;
  NOT _065_ (
    .A(data_in_Recir[16]),
    .Y(_000_)
  );
  NOT _066_ (
    .A(data_in_Recir[17]),
    .Y(_001_)
  );
  NOT _067_ (
    .A(data_in_Recir[18]),
    .Y(_002_)
  );
  NOT _068_ (
    .A(data_in_Recir[19]),
    .Y(_003_)
  );
  NOT _069_ (
    .A(data_in_Recir[20]),
    .Y(_004_)
  );
  NOT _070_ (
    .A(data_in_Recir[21]),
    .Y(_005_)
  );
  NOT _071_ (
    .A(data_in_Recir[22]),
    .Y(_006_)
  );
  NOT _072_ (
    .A(data_in_Recir[23]),
    .Y(_007_)
  );
  NOT _073_ (
    .A(data_in_Recir[24]),
    .Y(_008_)
  );
  NOT _074_ (
    .A(data_in_Recir[25]),
    .Y(_009_)
  );
  NOT _075_ (
    .A(data_in_Recir[26]),
    .Y(_010_)
  );
  NOT _076_ (
    .A(data_in_Recir[27]),
    .Y(_011_)
  );
  NOT _077_ (
    .A(data_in_Recir[28]),
    .Y(_012_)
  );
  NOT _078_ (
    .A(data_in_Recir[29]),
    .Y(_013_)
  );
  NOT _079_ (
    .A(data_in_Recir[30]),
    .Y(_014_)
  );
  NOT _080_ (
    .A(data_in_Recir[31]),
    .Y(_015_)
  );
  NOT _081_ (
    .A(data_in_Recir[0]),
    .Y(_016_)
  );
  NOT _082_ (
    .A(data_in_Recir[1]),
    .Y(_017_)
  );
  NOT _083_ (
    .A(data_in_Recir[2]),
    .Y(_018_)
  );
  NOT _084_ (
    .A(data_in_Recir[3]),
    .Y(_019_)
  );
  NOT _085_ (
    .A(data_in_Recir[4]),
    .Y(_020_)
  );
  NOT _086_ (
    .A(data_in_Recir[5]),
    .Y(_021_)
  );
  NOT _087_ (
    .A(data_in_Recir[6]),
    .Y(_022_)
  );
  NOT _088_ (
    .A(data_in_Recir[7]),
    .Y(_023_)
  );
  NOT _089_ (
    .A(data_in_Recir[8]),
    .Y(_024_)
  );
  NOT _090_ (
    .A(data_in_Recir[9]),
    .Y(_025_)
  );
  NOT _091_ (
    .A(data_in_Recir[10]),
    .Y(_026_)
  );
  NOT _092_ (
    .A(data_in_Recir[11]),
    .Y(_027_)
  );
  NOT _093_ (
    .A(data_in_Recir[12]),
    .Y(_028_)
  );
  NOT _094_ (
    .A(data_in_Recir[13]),
    .Y(_029_)
  );
  NOT _095_ (
    .A(data_in_Recir[14]),
    .Y(_030_)
  );
  NOT _096_ (
    .A(data_in_Recir[15]),
    .Y(_031_)
  );
  NOR _097_ (
    .A(_000_),
    .B(active),
    .Y(data_out_Retorno_Sint[16])
  );
  NOR _098_ (
    .A(active),
    .B(_001_),
    .Y(data_out_Retorno_Sint[17])
  );
  NOR _099_ (
    .A(active),
    .B(_002_),
    .Y(data_out_Retorno_Sint[18])
  );
  NOR _100_ (
    .A(active),
    .B(_003_),
    .Y(data_out_Retorno_Sint[19])
  );
  NOR _101_ (
    .A(active),
    .B(_004_),
    .Y(data_out_Retorno_Sint[20])
  );
  NOR _102_ (
    .A(active),
    .B(_005_),
    .Y(data_out_Retorno_Sint[21])
  );
  NOR _103_ (
    .A(active),
    .B(_006_),
    .Y(data_out_Retorno_Sint[22])
  );
  NOR _104_ (
    .A(active),
    .B(_007_),
    .Y(data_out_Retorno_Sint[23])
  );
  NOR _105_ (
    .A(active),
    .B(_008_),
    .Y(data_out_Retorno_Sint[24])
  );
  NOR _106_ (
    .A(active),
    .B(_009_),
    .Y(data_out_Retorno_Sint[25])
  );
  NOR _107_ (
    .A(active),
    .B(_010_),
    .Y(data_out_Retorno_Sint[26])
  );
  NOR _108_ (
    .A(active),
    .B(_011_),
    .Y(data_out_Retorno_Sint[27])
  );
  NOR _109_ (
    .A(active),
    .B(_012_),
    .Y(data_out_Retorno_Sint[28])
  );
  NOR _110_ (
    .A(active),
    .B(_013_),
    .Y(data_out_Retorno_Sint[29])
  );
  NOR _111_ (
    .A(active),
    .B(_014_),
    .Y(data_out_Retorno_Sint[30])
  );
  NOR _112_ (
    .A(active),
    .B(_015_),
    .Y(data_out_Retorno_Sint[31])
  );
  NAND _113_ (
    .A(active),
    .B(data_in_Recir[0]),
    .Y(_032_)
  );
  NOT _114_ (
    .A(_032_),
    .Y(data_out_Recir_Sint[0])
  );
  NAND _115_ (
    .A(active),
    .B(data_in_Recir[1]),
    .Y(_033_)
  );
  NOT _116_ (
    .A(_033_),
    .Y(data_out_Recir_Sint[1])
  );
  NAND _117_ (
    .A(active),
    .B(data_in_Recir[2]),
    .Y(_034_)
  );
  NOT _118_ (
    .A(_034_),
    .Y(data_out_Recir_Sint[2])
  );
  NAND _119_ (
    .A(active),
    .B(data_in_Recir[3]),
    .Y(_035_)
  );
  NOT _120_ (
    .A(_035_),
    .Y(data_out_Recir_Sint[3])
  );
  NAND _121_ (
    .A(active),
    .B(data_in_Recir[4]),
    .Y(_036_)
  );
  NOT _122_ (
    .A(_036_),
    .Y(data_out_Recir_Sint[4])
  );
  NAND _123_ (
    .A(active),
    .B(data_in_Recir[5]),
    .Y(_037_)
  );
  NOT _124_ (
    .A(_037_),
    .Y(data_out_Recir_Sint[5])
  );
  NAND _125_ (
    .A(active),
    .B(data_in_Recir[6]),
    .Y(_038_)
  );
  NOT _126_ (
    .A(_038_),
    .Y(data_out_Recir_Sint[6])
  );
  NAND _127_ (
    .A(active),
    .B(data_in_Recir[7]),
    .Y(_039_)
  );
  NOT _128_ (
    .A(_039_),
    .Y(data_out_Recir_Sint[7])
  );
  NAND _129_ (
    .A(active),
    .B(data_in_Recir[8]),
    .Y(_040_)
  );
  NOT _130_ (
    .A(_040_),
    .Y(data_out_Recir_Sint[8])
  );
  NAND _131_ (
    .A(active),
    .B(data_in_Recir[9]),
    .Y(_041_)
  );
  NOT _132_ (
    .A(_041_),
    .Y(data_out_Recir_Sint[9])
  );
  NAND _133_ (
    .A(active),
    .B(data_in_Recir[10]),
    .Y(_042_)
  );
  NOT _134_ (
    .A(_042_),
    .Y(data_out_Recir_Sint[10])
  );
  NAND _135_ (
    .A(active),
    .B(data_in_Recir[11]),
    .Y(_043_)
  );
  NOT _136_ (
    .A(_043_),
    .Y(data_out_Recir_Sint[11])
  );
  NAND _137_ (
    .A(active),
    .B(data_in_Recir[12]),
    .Y(_044_)
  );
  NOT _138_ (
    .A(_044_),
    .Y(data_out_Recir_Sint[12])
  );
  NAND _139_ (
    .A(active),
    .B(data_in_Recir[13]),
    .Y(_045_)
  );
  NOT _140_ (
    .A(_045_),
    .Y(data_out_Recir_Sint[13])
  );
  NAND _141_ (
    .A(active),
    .B(data_in_Recir[14]),
    .Y(_046_)
  );
  NOT _142_ (
    .A(_046_),
    .Y(data_out_Recir_Sint[14])
  );
  NAND _143_ (
    .A(active),
    .B(data_in_Recir[15]),
    .Y(_047_)
  );
  NOT _144_ (
    .A(_047_),
    .Y(data_out_Recir_Sint[15])
  );
  NAND _145_ (
    .A(data_in_Recir[16]),
    .B(active),
    .Y(_048_)
  );
  NOT _146_ (
    .A(_048_),
    .Y(data_out_Recir_Sint[16])
  );
  NAND _147_ (
    .A(active),
    .B(data_in_Recir[17]),
    .Y(_049_)
  );
  NOT _148_ (
    .A(_049_),
    .Y(data_out_Recir_Sint[17])
  );
  NAND _149_ (
    .A(active),
    .B(data_in_Recir[18]),
    .Y(_050_)
  );
  NOT _150_ (
    .A(_050_),
    .Y(data_out_Recir_Sint[18])
  );
  NAND _151_ (
    .A(active),
    .B(data_in_Recir[19]),
    .Y(_051_)
  );
  NOT _152_ (
    .A(_051_),
    .Y(data_out_Recir_Sint[19])
  );
  NAND _153_ (
    .A(active),
    .B(data_in_Recir[20]),
    .Y(_052_)
  );
  NOT _154_ (
    .A(_052_),
    .Y(data_out_Recir_Sint[20])
  );
  NAND _155_ (
    .A(active),
    .B(data_in_Recir[21]),
    .Y(_053_)
  );
  NOT _156_ (
    .A(_053_),
    .Y(data_out_Recir_Sint[21])
  );
  NAND _157_ (
    .A(active),
    .B(data_in_Recir[22]),
    .Y(_054_)
  );
  NOT _158_ (
    .A(_054_),
    .Y(data_out_Recir_Sint[22])
  );
  NAND _159_ (
    .A(active),
    .B(data_in_Recir[23]),
    .Y(_055_)
  );
  NOT _160_ (
    .A(_055_),
    .Y(data_out_Recir_Sint[23])
  );
  NAND _161_ (
    .A(active),
    .B(data_in_Recir[24]),
    .Y(_056_)
  );
  NOT _162_ (
    .A(_056_),
    .Y(data_out_Recir_Sint[24])
  );
  NAND _163_ (
    .A(active),
    .B(data_in_Recir[25]),
    .Y(_057_)
  );
  NOT _164_ (
    .A(_057_),
    .Y(data_out_Recir_Sint[25])
  );
  NAND _165_ (
    .A(active),
    .B(data_in_Recir[26]),
    .Y(_058_)
  );
  NOT _166_ (
    .A(_058_),
    .Y(data_out_Recir_Sint[26])
  );
  NAND _167_ (
    .A(active),
    .B(data_in_Recir[27]),
    .Y(_059_)
  );
  NOT _168_ (
    .A(_059_),
    .Y(data_out_Recir_Sint[27])
  );
  NAND _169_ (
    .A(active),
    .B(data_in_Recir[28]),
    .Y(_060_)
  );
  NOT _170_ (
    .A(_060_),
    .Y(data_out_Recir_Sint[28])
  );
  NAND _171_ (
    .A(active),
    .B(data_in_Recir[29]),
    .Y(_061_)
  );
  NOT _172_ (
    .A(_061_),
    .Y(data_out_Recir_Sint[29])
  );
  NAND _173_ (
    .A(active),
    .B(data_in_Recir[30]),
    .Y(_062_)
  );
  NOT _174_ (
    .A(_062_),
    .Y(data_out_Recir_Sint[30])
  );
  NAND _175_ (
    .A(active),
    .B(data_in_Recir[31]),
    .Y(_063_)
  );
  NOT _176_ (
    .A(_063_),
    .Y(data_out_Recir_Sint[31])
  );
  NAND _177_ (
    .A(active),
    .B(valid_in_Recir),
    .Y(_064_)
  );
  NOT _178_ (
    .A(_064_),
    .Y(valid_out_Recir_Sint)
  );
  NOR _179_ (
    .A(active),
    .B(_016_),
    .Y(data_out_Retorno_Sint[0])
  );
  NOR _180_ (
    .A(active),
    .B(_017_),
    .Y(data_out_Retorno_Sint[1])
  );
  NOR _181_ (
    .A(active),
    .B(_018_),
    .Y(data_out_Retorno_Sint[2])
  );
  NOR _182_ (
    .A(active),
    .B(_019_),
    .Y(data_out_Retorno_Sint[3])
  );
  NOR _183_ (
    .A(active),
    .B(_020_),
    .Y(data_out_Retorno_Sint[4])
  );
  NOR _184_ (
    .A(active),
    .B(_021_),
    .Y(data_out_Retorno_Sint[5])
  );
  NOR _185_ (
    .A(active),
    .B(_022_),
    .Y(data_out_Retorno_Sint[6])
  );
  NOR _186_ (
    .A(active),
    .B(_023_),
    .Y(data_out_Retorno_Sint[7])
  );
  NOR _187_ (
    .A(active),
    .B(_024_),
    .Y(data_out_Retorno_Sint[8])
  );
  NOR _188_ (
    .A(active),
    .B(_025_),
    .Y(data_out_Retorno_Sint[9])
  );
  NOR _189_ (
    .A(active),
    .B(_026_),
    .Y(data_out_Retorno_Sint[10])
  );
  NOR _190_ (
    .A(active),
    .B(_027_),
    .Y(data_out_Retorno_Sint[11])
  );
  NOR _191_ (
    .A(active),
    .B(_028_),
    .Y(data_out_Retorno_Sint[12])
  );
  NOR _192_ (
    .A(active),
    .B(_029_),
    .Y(data_out_Retorno_Sint[13])
  );
  NOR _193_ (
    .A(active),
    .B(_030_),
    .Y(data_out_Retorno_Sint[14])
  );
  NOR _194_ (
    .A(active),
    .B(_031_),
    .Y(data_out_Retorno_Sint[15])
  );
endmodule
