/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "module_PS.v:1" *)
module module_PS_Sint(clk_PS, reset_L, valid_in_PS, data_in_PS, data_out_PS_Sint);
  (* src = "module_PS.v:12" *)
  wire [2:0] _000_;
  (* src = "module_PS.v:12" *)
  (* unused_bits = "7" *)
  wire [7:0] _001_;
  (* src = "module_PS.v:12" *)
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  (* src = "module_PS.v:2" *)
  input clk_PS;
  (* src = "module_PS.v:10" *)
  wire [2:0] counter;
  (* src = "module_PS.v:8" *)
  (* unused_bits = "7" *)
  wire [7:0] data_in1_PS;
  (* src = "module_PS.v:9" *)
  wire [6:0] data_in2_PS;
  (* src = "module_PS.v:5" *)
  input [7:0] data_in_PS;
  (* src = "module_PS.v:6" *)
  output data_out_PS_Sint;
  (* src = "module_PS.v:3" *)
  input reset_L;
  (* src = "module_PS.v:4" *)
  input valid_in_PS;
  NOT _062_ (
    .A(data_in1_PS[6]),
    .Y(_004_)
  );
  NOT _063_ (
    .A(counter[2]),
    .Y(_005_)
  );
  NOT _064_ (
    .A(data_in_PS[5]),
    .Y(_006_)
  );
  NOT _065_ (
    .A(valid_in_PS),
    .Y(_007_)
  );
  NOT _066_ (
    .A(reset_L),
    .Y(_008_)
  );
  NOT _067_ (
    .A(data_in_PS[4]),
    .Y(_009_)
  );
  NOT _068_ (
    .A(data_in_PS[3]),
    .Y(_010_)
  );
  NOT _069_ (
    .A(data_in_PS[2]),
    .Y(_011_)
  );
  NOR _070_ (
    .A(data_in1_PS[0]),
    .B(data_in1_PS[3]),
    .Y(_012_)
  );
  NOR _071_ (
    .A(data_in1_PS[2]),
    .B(data_in1_PS[4]),
    .Y(_013_)
  );
  NAND _072_ (
    .A(_004_),
    .B(_013_),
    .Y(_014_)
  );
  NOR _073_ (
    .A(data_in1_PS[1]),
    .B(data_in1_PS[5]),
    .Y(_015_)
  );
  NAND _074_ (
    .A(_012_),
    .B(_015_),
    .Y(_016_)
  );
  NOR _075_ (
    .A(_014_),
    .B(_016_),
    .Y(_017_)
  );
  NAND _076_ (
    .A(counter[0]),
    .B(counter[1]),
    .Y(_018_)
  );
  NOT _077_ (
    .A(_018_),
    .Y(_019_)
  );
  NOR _078_ (
    .A(_005_),
    .B(_019_),
    .Y(_020_)
  );
  NAND _079_ (
    .A(counter[2]),
    .B(_018_),
    .Y(_021_)
  );
  NOR _080_ (
    .A(counter[0]),
    .B(counter[1]),
    .Y(_022_)
  );
  NOR _081_ (
    .A(counter[2]),
    .B(_022_),
    .Y(_023_)
  );
  NOT _082_ (
    .A(_023_),
    .Y(_024_)
  );
  NOR _083_ (
    .A(_020_),
    .B(_023_),
    .Y(_025_)
  );
  NAND _084_ (
    .A(_021_),
    .B(_024_),
    .Y(_026_)
  );
  NAND _085_ (
    .A(_006_),
    .B(valid_in_PS),
    .Y(_027_)
  );
  NOR _086_ (
    .A(_026_),
    .B(_027_),
    .Y(_028_)
  );
  NAND _087_ (
    .A(_017_),
    .B(_025_),
    .Y(_029_)
  );
  NOR _088_ (
    .A(_028_),
    .B(_029_),
    .Y(_030_)
  );
  NOR _089_ (
    .A(data_in1_PS[4]),
    .B(_030_),
    .Y(_031_)
  );
  NOR _090_ (
    .A(_008_),
    .B(_031_),
    .Y(_001_[5])
  );
  NAND _091_ (
    .A(valid_in_PS),
    .B(_009_),
    .Y(_032_)
  );
  NOR _092_ (
    .A(_026_),
    .B(_032_),
    .Y(_033_)
  );
  NOR _093_ (
    .A(_029_),
    .B(_033_),
    .Y(_034_)
  );
  NOR _094_ (
    .A(data_in1_PS[3]),
    .B(_034_),
    .Y(_035_)
  );
  NOR _095_ (
    .A(_008_),
    .B(_035_),
    .Y(_001_[4])
  );
  NAND _096_ (
    .A(valid_in_PS),
    .B(_010_),
    .Y(_036_)
  );
  NOR _097_ (
    .A(_026_),
    .B(_036_),
    .Y(_037_)
  );
  NOR _098_ (
    .A(_029_),
    .B(_037_),
    .Y(_038_)
  );
  NOR _099_ (
    .A(data_in1_PS[2]),
    .B(_038_),
    .Y(_039_)
  );
  NOR _100_ (
    .A(_008_),
    .B(_039_),
    .Y(_001_[3])
  );
  NAND _101_ (
    .A(valid_in_PS),
    .B(_011_),
    .Y(_040_)
  );
  NOR _102_ (
    .A(_026_),
    .B(_040_),
    .Y(_041_)
  );
  NOR _103_ (
    .A(_029_),
    .B(_041_),
    .Y(_042_)
  );
  NOR _104_ (
    .A(data_in1_PS[1]),
    .B(_042_),
    .Y(_043_)
  );
  NOR _105_ (
    .A(_008_),
    .B(_043_),
    .Y(_001_[2])
  );
  NAND _106_ (
    .A(valid_in_PS),
    .B(data_in_PS[1]),
    .Y(_044_)
  );
  NOR _107_ (
    .A(_029_),
    .B(_044_),
    .Y(_045_)
  );
  NOR _108_ (
    .A(data_in1_PS[0]),
    .B(_045_),
    .Y(_046_)
  );
  NOR _109_ (
    .A(_008_),
    .B(_046_),
    .Y(_001_[1])
  );
  NAND _110_ (
    .A(valid_in_PS),
    .B(data_in_PS[0]),
    .Y(_047_)
  );
  NOR _111_ (
    .A(_026_),
    .B(_047_),
    .Y(_048_)
  );
  NAND _112_ (
    .A(data_in1_PS[0]),
    .B(_026_),
    .Y(_049_)
  );
  NOT _113_ (
    .A(_049_),
    .Y(_050_)
  );
  NOR _114_ (
    .A(_048_),
    .B(_050_),
    .Y(_051_)
  );
  NAND _115_ (
    .A(reset_L),
    .B(_017_),
    .Y(_052_)
  );
  NOR _116_ (
    .A(_051_),
    .B(_052_),
    .Y(_001_[0])
  );
  NAND _117_ (
    .A(valid_in_PS),
    .B(data_in_PS[6]),
    .Y(_053_)
  );
  NOR _118_ (
    .A(_029_),
    .B(_053_),
    .Y(_054_)
  );
  NOR _119_ (
    .A(data_in1_PS[5]),
    .B(_054_),
    .Y(_055_)
  );
  NOR _120_ (
    .A(_008_),
    .B(_055_),
    .Y(_001_[6])
  );
  NOR _121_ (
    .A(_007_),
    .B(data_in_PS[7]),
    .Y(_056_)
  );
  NOR _122_ (
    .A(_029_),
    .B(_056_),
    .Y(_057_)
  );
  NOR _123_ (
    .A(data_in1_PS[6]),
    .B(_057_),
    .Y(_058_)
  );
  NOR _124_ (
    .A(_008_),
    .B(_058_),
    .Y(_002_)
  );
  NAND _125_ (
    .A(reset_L),
    .B(_029_),
    .Y(_059_)
  );
  NOR _126_ (
    .A(counter[0]),
    .B(_059_),
    .Y(_000_[0])
  );
  NAND _127_ (
    .A(reset_L),
    .B(_018_),
    .Y(_060_)
  );
  NOR _128_ (
    .A(_022_),
    .B(_060_),
    .Y(_000_[1])
  );
  NOR _129_ (
    .A(counter[2]),
    .B(_018_),
    .Y(_061_)
  );
  NOR _130_ (
    .A(_020_),
    .B(_061_),
    .Y(_003_)
  );
  NOR _131_ (
    .A(_008_),
    .B(_003_),
    .Y(_000_[2])
  );
  (* src = "module_PS.v:12" *)
  DFF _132_ (
    .C(clk_PS),
    .D(_000_[0]),
    .Q(counter[0])
  );
  (* src = "module_PS.v:12" *)
  DFF _133_ (
    .C(clk_PS),
    .D(_000_[1]),
    .Q(counter[1])
  );
  (* src = "module_PS.v:12" *)
  DFF _134_ (
    .C(clk_PS),
    .D(_000_[2]),
    .Q(counter[2])
  );
  (* src = "module_PS.v:12" *)
  DFF _135_ (
    .C(clk_PS),
    .D(_002_),
    .Q(data_out_PS_Sint)
  );
  (* src = "module_PS.v:12" *)
  DFF _136_ (
    .C(clk_PS),
    .D(_001_[0]),
    .Q(data_in1_PS[0])
  );
  (* src = "module_PS.v:12" *)
  DFF _137_ (
    .C(clk_PS),
    .D(_001_[1]),
    .Q(data_in1_PS[1])
  );
  (* src = "module_PS.v:12" *)
  DFF _138_ (
    .C(clk_PS),
    .D(_001_[2]),
    .Q(data_in1_PS[2])
  );
  (* src = "module_PS.v:12" *)
  DFF _139_ (
    .C(clk_PS),
    .D(_001_[3]),
    .Q(data_in1_PS[3])
  );
  (* src = "module_PS.v:12" *)
  DFF _140_ (
    .C(clk_PS),
    .D(_001_[4]),
    .Q(data_in1_PS[4])
  );
  (* src = "module_PS.v:12" *)
  DFF _141_ (
    .C(clk_PS),
    .D(_001_[5]),
    .Q(data_in1_PS[5])
  );
  (* src = "module_PS.v:12" *)
  DFF _142_ (
    .C(clk_PS),
    .D(_001_[6]),
    .Q(data_in1_PS[6])
  );
  assign data_in2_PS = 7'h00;
endmodule
