/* Generated by Yosys 0.9+3565 (git sha1 474cd02e, gcc 9.3.0-10ubuntu2 -fPIC -Os) */

(* top =  1  *)
(* src = "Mux8_32_synth.v:1.1-51.10" *)
module Mux8_32_synth(clk_f, clk_4f, data_in, valid_in, reset, data_out, valid_out);
  (* src = "Mux8_32_synth.v:39.1-48.4" *)
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  (* src = "Mux8_32_synth.v:3.11-3.17" *)
  input clk_4f;
  (* src = "Mux8_32_synth.v:2.11-2.16" *)
  input clk_f;
  (* src = "Mux8_32_synth.v:4.17-4.24" *)
  input [7:0] data_in;
  (* src = "Mux8_32_synth.v:7.23-7.31" *)
  output [31:0] data_out;
  (* src = "Mux8_32_synth.v:23.12-23.15" *)
  wire [31:0] mem;
  (* src = "Mux8_32_synth.v:6.11-6.16" *)
  input reset;
  (* src = "Mux8_32_synth.v:5.11-5.19" *)
  input valid_in;
  (* src = "Mux8_32_synth.v:8.16-8.25" *)
  output valid_out;
  NOT _162_ (
    .A(mem[30]),
    .Y(_097_)
  );
  NOT _163_ (
    .A(mem[29]),
    .Y(_098_)
  );
  NOT _164_ (
    .A(mem[28]),
    .Y(_099_)
  );
  NOT _165_ (
    .A(mem[27]),
    .Y(_100_)
  );
  NOT _166_ (
    .A(mem[26]),
    .Y(_101_)
  );
  NOT _167_ (
    .A(mem[25]),
    .Y(_102_)
  );
  NOT _168_ (
    .A(mem[24]),
    .Y(_103_)
  );
  NOT _169_ (
    .A(mem[23]),
    .Y(_104_)
  );
  NOT _170_ (
    .A(mem[22]),
    .Y(_105_)
  );
  NOT _171_ (
    .A(mem[21]),
    .Y(_106_)
  );
  NOT _172_ (
    .A(mem[20]),
    .Y(_107_)
  );
  NOT _173_ (
    .A(mem[19]),
    .Y(_108_)
  );
  NOT _174_ (
    .A(mem[18]),
    .Y(_109_)
  );
  NOT _175_ (
    .A(mem[17]),
    .Y(_110_)
  );
  NOT _176_ (
    .A(mem[16]),
    .Y(_111_)
  );
  NOT _177_ (
    .A(mem[15]),
    .Y(_112_)
  );
  NOT _178_ (
    .A(mem[14]),
    .Y(_113_)
  );
  NOT _179_ (
    .A(mem[13]),
    .Y(_114_)
  );
  NOT _180_ (
    .A(mem[12]),
    .Y(_115_)
  );
  NOT _181_ (
    .A(mem[11]),
    .Y(_116_)
  );
  NOT _182_ (
    .A(mem[10]),
    .Y(_117_)
  );
  NOT _183_ (
    .A(mem[9]),
    .Y(_118_)
  );
  NOT _184_ (
    .A(mem[8]),
    .Y(_119_)
  );
  NOT _185_ (
    .A(mem[7]),
    .Y(_120_)
  );
  NOT _186_ (
    .A(mem[6]),
    .Y(_121_)
  );
  NOT _187_ (
    .A(mem[5]),
    .Y(_122_)
  );
  NOT _188_ (
    .A(mem[4]),
    .Y(_123_)
  );
  NOT _189_ (
    .A(mem[3]),
    .Y(_124_)
  );
  NOT _190_ (
    .A(mem[2]),
    .Y(_125_)
  );
  NOT _191_ (
    .A(mem[1]),
    .Y(_126_)
  );
  NOT _192_ (
    .A(mem[0]),
    .Y(_127_)
  );
  NOT _193_ (
    .A(clk_4f),
    .Y(_032_)
  );
  NOT _194_ (
    .A(mem[31]),
    .Y(_128_)
  );
  NAND _195_ (
    .A(valid_in),
    .B(reset),
    .Y(_129_)
  );
  NOT _196_ (
    .A(_129_),
    .Y(_000_)
  );
  NOR _197_ (
    .A(_097_),
    .B(_129_),
    .Y(_095_)
  );
  NOR _198_ (
    .A(_098_),
    .B(_129_),
    .Y(_094_)
  );
  NOR _199_ (
    .A(_099_),
    .B(_129_),
    .Y(_093_)
  );
  NOR _200_ (
    .A(_100_),
    .B(_129_),
    .Y(_092_)
  );
  NOR _201_ (
    .A(_101_),
    .B(_129_),
    .Y(_091_)
  );
  NOR _202_ (
    .A(_102_),
    .B(_129_),
    .Y(_090_)
  );
  NOR _203_ (
    .A(_103_),
    .B(_129_),
    .Y(_089_)
  );
  NAND _204_ (
    .A(mem[23]),
    .B(valid_in),
    .Y(_130_)
  );
  NOT _205_ (
    .A(_130_),
    .Y(_064_)
  );
  NOR _206_ (
    .A(_104_),
    .B(_129_),
    .Y(_088_)
  );
  NAND _207_ (
    .A(mem[22]),
    .B(valid_in),
    .Y(_131_)
  );
  NOT _208_ (
    .A(_131_),
    .Y(_063_)
  );
  NOR _209_ (
    .A(_105_),
    .B(_129_),
    .Y(_087_)
  );
  NAND _210_ (
    .A(mem[21]),
    .B(valid_in),
    .Y(_132_)
  );
  NOT _211_ (
    .A(_132_),
    .Y(_062_)
  );
  NOR _212_ (
    .A(_106_),
    .B(_129_),
    .Y(_086_)
  );
  NAND _213_ (
    .A(mem[20]),
    .B(valid_in),
    .Y(_133_)
  );
  NOT _214_ (
    .A(_133_),
    .Y(_061_)
  );
  NOR _215_ (
    .A(_107_),
    .B(_129_),
    .Y(_085_)
  );
  NAND _216_ (
    .A(mem[19]),
    .B(valid_in),
    .Y(_134_)
  );
  NOT _217_ (
    .A(_134_),
    .Y(_060_)
  );
  NOR _218_ (
    .A(_108_),
    .B(_129_),
    .Y(_084_)
  );
  NAND _219_ (
    .A(mem[18]),
    .B(valid_in),
    .Y(_135_)
  );
  NOT _220_ (
    .A(_135_),
    .Y(_059_)
  );
  NOR _221_ (
    .A(_109_),
    .B(_129_),
    .Y(_083_)
  );
  NAND _222_ (
    .A(mem[17]),
    .B(valid_in),
    .Y(_136_)
  );
  NOT _223_ (
    .A(_136_),
    .Y(_058_)
  );
  NOR _224_ (
    .A(_110_),
    .B(_129_),
    .Y(_082_)
  );
  NAND _225_ (
    .A(mem[16]),
    .B(valid_in),
    .Y(_137_)
  );
  NOT _226_ (
    .A(_137_),
    .Y(_057_)
  );
  NOR _227_ (
    .A(_111_),
    .B(_129_),
    .Y(_081_)
  );
  NAND _228_ (
    .A(mem[15]),
    .B(valid_in),
    .Y(_138_)
  );
  NOT _229_ (
    .A(_138_),
    .Y(_056_)
  );
  NOR _230_ (
    .A(_112_),
    .B(_129_),
    .Y(_080_)
  );
  NAND _231_ (
    .A(mem[14]),
    .B(valid_in),
    .Y(_139_)
  );
  NOT _232_ (
    .A(_139_),
    .Y(_055_)
  );
  NOR _233_ (
    .A(_113_),
    .B(_129_),
    .Y(_079_)
  );
  NAND _234_ (
    .A(mem[13]),
    .B(valid_in),
    .Y(_140_)
  );
  NOT _235_ (
    .A(_140_),
    .Y(_054_)
  );
  NOR _236_ (
    .A(_114_),
    .B(_129_),
    .Y(_078_)
  );
  NAND _237_ (
    .A(mem[12]),
    .B(valid_in),
    .Y(_141_)
  );
  NOT _238_ (
    .A(_141_),
    .Y(_053_)
  );
  NOR _239_ (
    .A(_115_),
    .B(_129_),
    .Y(_077_)
  );
  NAND _240_ (
    .A(mem[11]),
    .B(valid_in),
    .Y(_142_)
  );
  NOT _241_ (
    .A(_142_),
    .Y(_052_)
  );
  NOR _242_ (
    .A(_116_),
    .B(_129_),
    .Y(_076_)
  );
  NAND _243_ (
    .A(mem[10]),
    .B(valid_in),
    .Y(_143_)
  );
  NOT _244_ (
    .A(_143_),
    .Y(_051_)
  );
  NOR _245_ (
    .A(_117_),
    .B(_129_),
    .Y(_075_)
  );
  NAND _246_ (
    .A(mem[9]),
    .B(valid_in),
    .Y(_144_)
  );
  NOT _247_ (
    .A(_144_),
    .Y(_050_)
  );
  NOR _248_ (
    .A(_118_),
    .B(_129_),
    .Y(_074_)
  );
  NAND _249_ (
    .A(mem[8]),
    .B(valid_in),
    .Y(_145_)
  );
  NOT _250_ (
    .A(_145_),
    .Y(_049_)
  );
  NOR _251_ (
    .A(_119_),
    .B(_129_),
    .Y(_073_)
  );
  NAND _252_ (
    .A(mem[7]),
    .B(valid_in),
    .Y(_146_)
  );
  NOT _253_ (
    .A(_146_),
    .Y(_048_)
  );
  NOR _254_ (
    .A(_120_),
    .B(_129_),
    .Y(_072_)
  );
  NAND _255_ (
    .A(mem[6]),
    .B(valid_in),
    .Y(_147_)
  );
  NOT _256_ (
    .A(_147_),
    .Y(_047_)
  );
  NOR _257_ (
    .A(_121_),
    .B(_129_),
    .Y(_071_)
  );
  NAND _258_ (
    .A(mem[5]),
    .B(valid_in),
    .Y(_148_)
  );
  NOT _259_ (
    .A(_148_),
    .Y(_046_)
  );
  NOR _260_ (
    .A(_122_),
    .B(_129_),
    .Y(_070_)
  );
  NAND _261_ (
    .A(mem[4]),
    .B(valid_in),
    .Y(_149_)
  );
  NOT _262_ (
    .A(_149_),
    .Y(_045_)
  );
  NOR _263_ (
    .A(_123_),
    .B(_129_),
    .Y(_069_)
  );
  NAND _264_ (
    .A(mem[3]),
    .B(valid_in),
    .Y(_150_)
  );
  NOT _265_ (
    .A(_150_),
    .Y(_044_)
  );
  NOR _266_ (
    .A(_124_),
    .B(_129_),
    .Y(_068_)
  );
  NAND _267_ (
    .A(mem[2]),
    .B(valid_in),
    .Y(_151_)
  );
  NOT _268_ (
    .A(_151_),
    .Y(_043_)
  );
  NOR _269_ (
    .A(_125_),
    .B(_129_),
    .Y(_067_)
  );
  NAND _270_ (
    .A(mem[1]),
    .B(valid_in),
    .Y(_152_)
  );
  NOT _271_ (
    .A(_152_),
    .Y(_042_)
  );
  NOR _272_ (
    .A(_126_),
    .B(_129_),
    .Y(_066_)
  );
  NAND _273_ (
    .A(mem[0]),
    .B(valid_in),
    .Y(_153_)
  );
  NOT _274_ (
    .A(_153_),
    .Y(_041_)
  );
  NOR _275_ (
    .A(_127_),
    .B(_129_),
    .Y(_065_)
  );
  NAND _276_ (
    .A(valid_in),
    .B(data_in[7]),
    .Y(_154_)
  );
  NOT _277_ (
    .A(_154_),
    .Y(_040_)
  );
  NAND _278_ (
    .A(valid_in),
    .B(data_in[6]),
    .Y(_155_)
  );
  NOT _279_ (
    .A(_155_),
    .Y(_039_)
  );
  NAND _280_ (
    .A(valid_in),
    .B(data_in[5]),
    .Y(_156_)
  );
  NOT _281_ (
    .A(_156_),
    .Y(_038_)
  );
  NAND _282_ (
    .A(valid_in),
    .B(data_in[4]),
    .Y(_157_)
  );
  NOT _283_ (
    .A(_157_),
    .Y(_037_)
  );
  NAND _284_ (
    .A(valid_in),
    .B(data_in[3]),
    .Y(_158_)
  );
  NOT _285_ (
    .A(_158_),
    .Y(_036_)
  );
  NAND _286_ (
    .A(valid_in),
    .B(data_in[2]),
    .Y(_159_)
  );
  NOT _287_ (
    .A(_159_),
    .Y(_035_)
  );
  NAND _288_ (
    .A(valid_in),
    .B(data_in[1]),
    .Y(_160_)
  );
  NOT _289_ (
    .A(_160_),
    .Y(_034_)
  );
  NAND _290_ (
    .A(valid_in),
    .B(data_in[0]),
    .Y(_161_)
  );
  NOT _291_ (
    .A(_161_),
    .Y(_033_)
  );
  NOR _292_ (
    .A(_128_),
    .B(_129_),
    .Y(_096_)
  );
  NOT _293_ (
    .A(clk_4f),
    .Y(_031_)
  );
  NOT _294_ (
    .A(clk_4f),
    .Y(_030_)
  );
  NOT _295_ (
    .A(clk_4f),
    .Y(_029_)
  );
  NOT _296_ (
    .A(clk_4f),
    .Y(_028_)
  );
  NOT _297_ (
    .A(clk_4f),
    .Y(_027_)
  );
  NOT _298_ (
    .A(clk_4f),
    .Y(_026_)
  );
  NOT _299_ (
    .A(clk_4f),
    .Y(_025_)
  );
  NOT _300_ (
    .A(clk_4f),
    .Y(_024_)
  );
  NOT _301_ (
    .A(clk_4f),
    .Y(_023_)
  );
  NOT _302_ (
    .A(clk_4f),
    .Y(_022_)
  );
  NOT _303_ (
    .A(clk_4f),
    .Y(_021_)
  );
  NOT _304_ (
    .A(clk_4f),
    .Y(_020_)
  );
  NOT _305_ (
    .A(clk_4f),
    .Y(_019_)
  );
  NOT _306_ (
    .A(clk_4f),
    .Y(_018_)
  );
  NOT _307_ (
    .A(clk_4f),
    .Y(_017_)
  );
  NOT _308_ (
    .A(clk_4f),
    .Y(_016_)
  );
  NOT _309_ (
    .A(clk_4f),
    .Y(_015_)
  );
  NOT _310_ (
    .A(clk_4f),
    .Y(_014_)
  );
  NOT _311_ (
    .A(clk_4f),
    .Y(_013_)
  );
  NOT _312_ (
    .A(clk_4f),
    .Y(_012_)
  );
  NOT _313_ (
    .A(clk_4f),
    .Y(_011_)
  );
  NOT _314_ (
    .A(clk_4f),
    .Y(_010_)
  );
  NOT _315_ (
    .A(clk_4f),
    .Y(_009_)
  );
  NOT _316_ (
    .A(clk_4f),
    .Y(_008_)
  );
  NOT _317_ (
    .A(clk_4f),
    .Y(_007_)
  );
  NOT _318_ (
    .A(clk_4f),
    .Y(_006_)
  );
  NOT _319_ (
    .A(clk_4f),
    .Y(_005_)
  );
  NOT _320_ (
    .A(clk_4f),
    .Y(_004_)
  );
  NOT _321_ (
    .A(clk_4f),
    .Y(_003_)
  );
  NOT _322_ (
    .A(clk_4f),
    .Y(_002_)
  );
  NOT _323_ (
    .A(clk_4f),
    .Y(_001_)
  );
  (* src = "Mux8_32_synth.v:39.1-48.4" *)
  DFF _324_ (
    .C(clk_f),
    .D(_000_),
    .Q(valid_out)
  );
  (* src = "Mux8_32_synth.v:24.1-34.4" *)
  DFF _325_ (
    .C(_001_),
    .D(_033_),
    .Q(mem[0])
  );
  (* src = "Mux8_32_synth.v:24.1-34.4" *)
  DFF _326_ (
    .C(_002_),
    .D(_034_),
    .Q(mem[1])
  );
  (* src = "Mux8_32_synth.v:24.1-34.4" *)
  DFF _327_ (
    .C(_003_),
    .D(_035_),
    .Q(mem[2])
  );
  (* src = "Mux8_32_synth.v:24.1-34.4" *)
  DFF _328_ (
    .C(_004_),
    .D(_036_),
    .Q(mem[3])
  );
  (* src = "Mux8_32_synth.v:24.1-34.4" *)
  DFF _329_ (
    .C(_005_),
    .D(_037_),
    .Q(mem[4])
  );
  (* src = "Mux8_32_synth.v:24.1-34.4" *)
  DFF _330_ (
    .C(_006_),
    .D(_038_),
    .Q(mem[5])
  );
  (* src = "Mux8_32_synth.v:24.1-34.4" *)
  DFF _331_ (
    .C(_007_),
    .D(_039_),
    .Q(mem[6])
  );
  (* src = "Mux8_32_synth.v:24.1-34.4" *)
  DFF _332_ (
    .C(_008_),
    .D(_040_),
    .Q(mem[7])
  );
  (* src = "Mux8_32_synth.v:24.1-34.4" *)
  DFF _333_ (
    .C(_009_),
    .D(_041_),
    .Q(mem[8])
  );
  (* src = "Mux8_32_synth.v:24.1-34.4" *)
  DFF _334_ (
    .C(_010_),
    .D(_042_),
    .Q(mem[9])
  );
  (* src = "Mux8_32_synth.v:24.1-34.4" *)
  DFF _335_ (
    .C(_011_),
    .D(_043_),
    .Q(mem[10])
  );
  (* src = "Mux8_32_synth.v:24.1-34.4" *)
  DFF _336_ (
    .C(_012_),
    .D(_044_),
    .Q(mem[11])
  );
  (* src = "Mux8_32_synth.v:24.1-34.4" *)
  DFF _337_ (
    .C(_013_),
    .D(_045_),
    .Q(mem[12])
  );
  (* src = "Mux8_32_synth.v:24.1-34.4" *)
  DFF _338_ (
    .C(_014_),
    .D(_046_),
    .Q(mem[13])
  );
  (* src = "Mux8_32_synth.v:24.1-34.4" *)
  DFF _339_ (
    .C(_015_),
    .D(_047_),
    .Q(mem[14])
  );
  (* src = "Mux8_32_synth.v:24.1-34.4" *)
  DFF _340_ (
    .C(_016_),
    .D(_048_),
    .Q(mem[15])
  );
  (* src = "Mux8_32_synth.v:24.1-34.4" *)
  DFF _341_ (
    .C(_017_),
    .D(_049_),
    .Q(mem[16])
  );
  (* src = "Mux8_32_synth.v:24.1-34.4" *)
  DFF _342_ (
    .C(_018_),
    .D(_050_),
    .Q(mem[17])
  );
  (* src = "Mux8_32_synth.v:24.1-34.4" *)
  DFF _343_ (
    .C(_019_),
    .D(_051_),
    .Q(mem[18])
  );
  (* src = "Mux8_32_synth.v:24.1-34.4" *)
  DFF _344_ (
    .C(_020_),
    .D(_052_),
    .Q(mem[19])
  );
  (* src = "Mux8_32_synth.v:24.1-34.4" *)
  DFF _345_ (
    .C(_021_),
    .D(_053_),
    .Q(mem[20])
  );
  (* src = "Mux8_32_synth.v:24.1-34.4" *)
  DFF _346_ (
    .C(_022_),
    .D(_054_),
    .Q(mem[21])
  );
  (* src = "Mux8_32_synth.v:24.1-34.4" *)
  DFF _347_ (
    .C(_023_),
    .D(_055_),
    .Q(mem[22])
  );
  (* src = "Mux8_32_synth.v:24.1-34.4" *)
  DFF _348_ (
    .C(_024_),
    .D(_056_),
    .Q(mem[23])
  );
  (* src = "Mux8_32_synth.v:24.1-34.4" *)
  DFF _349_ (
    .C(_025_),
    .D(_057_),
    .Q(mem[24])
  );
  (* src = "Mux8_32_synth.v:24.1-34.4" *)
  DFF _350_ (
    .C(_026_),
    .D(_058_),
    .Q(mem[25])
  );
  (* src = "Mux8_32_synth.v:24.1-34.4" *)
  DFF _351_ (
    .C(_027_),
    .D(_059_),
    .Q(mem[26])
  );
  (* src = "Mux8_32_synth.v:24.1-34.4" *)
  DFF _352_ (
    .C(_028_),
    .D(_060_),
    .Q(mem[27])
  );
  (* src = "Mux8_32_synth.v:24.1-34.4" *)
  DFF _353_ (
    .C(_029_),
    .D(_061_),
    .Q(mem[28])
  );
  (* src = "Mux8_32_synth.v:24.1-34.4" *)
  DFF _354_ (
    .C(_030_),
    .D(_062_),
    .Q(mem[29])
  );
  (* src = "Mux8_32_synth.v:24.1-34.4" *)
  DFF _355_ (
    .C(_031_),
    .D(_063_),
    .Q(mem[30])
  );
  (* src = "Mux8_32_synth.v:24.1-34.4" *)
  DFF _356_ (
    .C(_032_),
    .D(_064_),
    .Q(mem[31])
  );
  (* src = "Mux8_32_synth.v:39.1-48.4" *)
  DFF _357_ (
    .C(clk_f),
    .D(_065_),
    .Q(data_out[0])
  );
  (* src = "Mux8_32_synth.v:39.1-48.4" *)
  DFF _358_ (
    .C(clk_f),
    .D(_066_),
    .Q(data_out[1])
  );
  (* src = "Mux8_32_synth.v:39.1-48.4" *)
  DFF _359_ (
    .C(clk_f),
    .D(_067_),
    .Q(data_out[2])
  );
  (* src = "Mux8_32_synth.v:39.1-48.4" *)
  DFF _360_ (
    .C(clk_f),
    .D(_068_),
    .Q(data_out[3])
  );
  (* src = "Mux8_32_synth.v:39.1-48.4" *)
  DFF _361_ (
    .C(clk_f),
    .D(_069_),
    .Q(data_out[4])
  );
  (* src = "Mux8_32_synth.v:39.1-48.4" *)
  DFF _362_ (
    .C(clk_f),
    .D(_070_),
    .Q(data_out[5])
  );
  (* src = "Mux8_32_synth.v:39.1-48.4" *)
  DFF _363_ (
    .C(clk_f),
    .D(_071_),
    .Q(data_out[6])
  );
  (* src = "Mux8_32_synth.v:39.1-48.4" *)
  DFF _364_ (
    .C(clk_f),
    .D(_072_),
    .Q(data_out[7])
  );
  (* src = "Mux8_32_synth.v:39.1-48.4" *)
  DFF _365_ (
    .C(clk_f),
    .D(_073_),
    .Q(data_out[8])
  );
  (* src = "Mux8_32_synth.v:39.1-48.4" *)
  DFF _366_ (
    .C(clk_f),
    .D(_074_),
    .Q(data_out[9])
  );
  (* src = "Mux8_32_synth.v:39.1-48.4" *)
  DFF _367_ (
    .C(clk_f),
    .D(_075_),
    .Q(data_out[10])
  );
  (* src = "Mux8_32_synth.v:39.1-48.4" *)
  DFF _368_ (
    .C(clk_f),
    .D(_076_),
    .Q(data_out[11])
  );
  (* src = "Mux8_32_synth.v:39.1-48.4" *)
  DFF _369_ (
    .C(clk_f),
    .D(_077_),
    .Q(data_out[12])
  );
  (* src = "Mux8_32_synth.v:39.1-48.4" *)
  DFF _370_ (
    .C(clk_f),
    .D(_078_),
    .Q(data_out[13])
  );
  (* src = "Mux8_32_synth.v:39.1-48.4" *)
  DFF _371_ (
    .C(clk_f),
    .D(_079_),
    .Q(data_out[14])
  );
  (* src = "Mux8_32_synth.v:39.1-48.4" *)
  DFF _372_ (
    .C(clk_f),
    .D(_080_),
    .Q(data_out[15])
  );
  (* src = "Mux8_32_synth.v:39.1-48.4" *)
  DFF _373_ (
    .C(clk_f),
    .D(_081_),
    .Q(data_out[16])
  );
  (* src = "Mux8_32_synth.v:39.1-48.4" *)
  DFF _374_ (
    .C(clk_f),
    .D(_082_),
    .Q(data_out[17])
  );
  (* src = "Mux8_32_synth.v:39.1-48.4" *)
  DFF _375_ (
    .C(clk_f),
    .D(_083_),
    .Q(data_out[18])
  );
  (* src = "Mux8_32_synth.v:39.1-48.4" *)
  DFF _376_ (
    .C(clk_f),
    .D(_084_),
    .Q(data_out[19])
  );
  (* src = "Mux8_32_synth.v:39.1-48.4" *)
  DFF _377_ (
    .C(clk_f),
    .D(_085_),
    .Q(data_out[20])
  );
  (* src = "Mux8_32_synth.v:39.1-48.4" *)
  DFF _378_ (
    .C(clk_f),
    .D(_086_),
    .Q(data_out[21])
  );
  (* src = "Mux8_32_synth.v:39.1-48.4" *)
  DFF _379_ (
    .C(clk_f),
    .D(_087_),
    .Q(data_out[22])
  );
  (* src = "Mux8_32_synth.v:39.1-48.4" *)
  DFF _380_ (
    .C(clk_f),
    .D(_088_),
    .Q(data_out[23])
  );
  (* src = "Mux8_32_synth.v:39.1-48.4" *)
  DFF _381_ (
    .C(clk_f),
    .D(_089_),
    .Q(data_out[24])
  );
  (* src = "Mux8_32_synth.v:39.1-48.4" *)
  DFF _382_ (
    .C(clk_f),
    .D(_090_),
    .Q(data_out[25])
  );
  (* src = "Mux8_32_synth.v:39.1-48.4" *)
  DFF _383_ (
    .C(clk_f),
    .D(_091_),
    .Q(data_out[26])
  );
  (* src = "Mux8_32_synth.v:39.1-48.4" *)
  DFF _384_ (
    .C(clk_f),
    .D(_092_),
    .Q(data_out[27])
  );
  (* src = "Mux8_32_synth.v:39.1-48.4" *)
  DFF _385_ (
    .C(clk_f),
    .D(_093_),
    .Q(data_out[28])
  );
  (* src = "Mux8_32_synth.v:39.1-48.4" *)
  DFF _386_ (
    .C(clk_f),
    .D(_094_),
    .Q(data_out[29])
  );
  (* src = "Mux8_32_synth.v:39.1-48.4" *)
  DFF _387_ (
    .C(clk_f),
    .D(_095_),
    .Q(data_out[30])
  );
  (* src = "Mux8_32_synth.v:39.1-48.4" *)
  DFF _388_ (
    .C(clk_f),
    .D(_096_),
    .Q(data_out[31])
  );
endmodule
