/* Generated by Yosys 0.9+3565 (git sha1 474cd02e, gcc 9.3.0-10ubuntu2 -fPIC -Os) */

(* top =  1  *)
(* src = "Mux8_32_synth.v:1.1-95.10" *)
module Mux8_32_synth(clk_f, clk_4f, data_in, valid_in, data_out, valid_out);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  (* src = "Mux8_32_synth.v:33.11-33.13" *)
  wire [7:0] A1;
  (* src = "Mux8_32_synth.v:34.11-34.13" *)
  wire [7:0] A2;
  (* src = "Mux8_32_synth.v:35.11-35.13" *)
  wire [7:0] A3;
  (* src = "Mux8_32_synth.v:37.12-37.18" *)
  wire [31:0] buffer;
  (* src = "Mux8_32_synth.v:3.11-3.17" *)
  input clk_4f;
  (* src = "Mux8_32_synth.v:2.11-2.16" *)
  input clk_f;
  (* init = 3'h0 *)
  (* src = "Mux8_32_synth.v:10.11-10.18" *)
  wire [2:0] counter;
  (* src = "Mux8_32_synth.v:4.17-4.24" *)
  input [7:0] data_in;
  (* src = "Mux8_32_synth.v:6.23-6.31" *)
  output [31:0] data_out;
  (* src = "Mux8_32_synth.v:40.5-40.9" *)
  wire flag;
  (* src = "Mux8_32_synth.v:79.5-79.10" *)
  wire flag2;
  (* src = "Mux8_32_synth.v:5.11-5.19" *)
  input valid_in;
  (* src = "Mux8_32_synth.v:7.16-7.25" *)
  output valid_out;
  NOT _201_ (
    .A(clk_4f),
    .Y(_002_)
  );
  NOT _202_ (
    .A(valid_in),
    .Y(_063_)
  );
  NOT _203_ (
    .A(counter[2]),
    .Y(_064_)
  );
  NOT _204_ (
    .A(counter[0]),
    .Y(_065_)
  );
  NOT _205_ (
    .A(counter[1]),
    .Y(_066_)
  );
  NOT _206_ (
    .A(flag2),
    .Y(_067_)
  );
  NOR _207_ (
    .A(_063_),
    .B(counter[0]),
    .Y(_061_)
  );
  NAND _208_ (
    .A(counter[0]),
    .B(counter[1]),
    .Y(_068_)
  );
  NOR _209_ (
    .A(counter[2]),
    .B(_065_),
    .Y(_069_)
  );
  NAND _210_ (
    .A(_064_),
    .B(counter[0]),
    .Y(_070_)
  );
  NOR _211_ (
    .A(counter[2]),
    .B(_068_),
    .Y(_071_)
  );
  NAND _212_ (
    .A(counter[1]),
    .B(_069_),
    .Y(_072_)
  );
  NAND _213_ (
    .A(counter[2]),
    .B(_068_),
    .Y(_073_)
  );
  NOT _214_ (
    .A(_073_),
    .Y(_074_)
  );
  NOR _215_ (
    .A(_071_),
    .B(_074_),
    .Y(_075_)
  );
  NOR _216_ (
    .A(counter[0]),
    .B(counter[1]),
    .Y(_076_)
  );
  NOT _217_ (
    .A(_076_),
    .Y(_077_)
  );
  NOR _218_ (
    .A(_064_),
    .B(_077_),
    .Y(_078_)
  );
  NAND _219_ (
    .A(counter[2]),
    .B(_076_),
    .Y(_079_)
  );
  NAND _220_ (
    .A(valid_in),
    .B(_079_),
    .Y(_080_)
  );
  NOR _221_ (
    .A(_075_),
    .B(_080_),
    .Y(_060_)
  );
  NAND _222_ (
    .A(valid_in),
    .B(_068_),
    .Y(_081_)
  );
  NOR _223_ (
    .A(_076_),
    .B(_081_),
    .Y(_059_)
  );
  NOR _224_ (
    .A(counter[2]),
    .B(counter[0]),
    .Y(_082_)
  );
  NAND _225_ (
    .A(_064_),
    .B(_065_),
    .Y(_083_)
  );
  NOR _226_ (
    .A(_066_),
    .B(_083_),
    .Y(_084_)
  );
  NAND _227_ (
    .A(counter[1]),
    .B(_082_),
    .Y(_085_)
  );
  NAND _228_ (
    .A(data_in[7]),
    .B(_084_),
    .Y(_086_)
  );
  NAND _229_ (
    .A(A2[7]),
    .B(_085_),
    .Y(_087_)
  );
  NAND _230_ (
    .A(_086_),
    .B(_087_),
    .Y(_058_)
  );
  NAND _231_ (
    .A(data_in[6]),
    .B(_084_),
    .Y(_088_)
  );
  NAND _232_ (
    .A(A2[6]),
    .B(_085_),
    .Y(_089_)
  );
  NAND _233_ (
    .A(_088_),
    .B(_089_),
    .Y(_057_)
  );
  NAND _234_ (
    .A(data_in[5]),
    .B(_084_),
    .Y(_090_)
  );
  NAND _235_ (
    .A(A2[5]),
    .B(_085_),
    .Y(_091_)
  );
  NAND _236_ (
    .A(_090_),
    .B(_091_),
    .Y(_056_)
  );
  NAND _237_ (
    .A(data_in[4]),
    .B(_084_),
    .Y(_092_)
  );
  NAND _238_ (
    .A(A2[4]),
    .B(_085_),
    .Y(_093_)
  );
  NAND _239_ (
    .A(_092_),
    .B(_093_),
    .Y(_055_)
  );
  NAND _240_ (
    .A(data_in[3]),
    .B(_084_),
    .Y(_094_)
  );
  NAND _241_ (
    .A(A2[3]),
    .B(_085_),
    .Y(_095_)
  );
  NAND _242_ (
    .A(_094_),
    .B(_095_),
    .Y(_054_)
  );
  NAND _243_ (
    .A(data_in[2]),
    .B(_084_),
    .Y(_096_)
  );
  NAND _244_ (
    .A(A2[2]),
    .B(_085_),
    .Y(_097_)
  );
  NAND _245_ (
    .A(_096_),
    .B(_097_),
    .Y(_053_)
  );
  NAND _246_ (
    .A(data_in[1]),
    .B(_084_),
    .Y(_098_)
  );
  NAND _247_ (
    .A(A2[1]),
    .B(_085_),
    .Y(_099_)
  );
  NAND _248_ (
    .A(_098_),
    .B(_099_),
    .Y(_052_)
  );
  NAND _249_ (
    .A(data_in[0]),
    .B(_084_),
    .Y(_100_)
  );
  NAND _250_ (
    .A(A2[0]),
    .B(_085_),
    .Y(_101_)
  );
  NAND _251_ (
    .A(_100_),
    .B(_101_),
    .Y(_051_)
  );
  NAND _252_ (
    .A(data_in[7]),
    .B(_071_),
    .Y(_102_)
  );
  NAND _253_ (
    .A(A3[7]),
    .B(_072_),
    .Y(_103_)
  );
  NAND _254_ (
    .A(_102_),
    .B(_103_),
    .Y(_050_)
  );
  NAND _255_ (
    .A(data_in[6]),
    .B(_071_),
    .Y(_104_)
  );
  NAND _256_ (
    .A(A3[6]),
    .B(_072_),
    .Y(_105_)
  );
  NAND _257_ (
    .A(_104_),
    .B(_105_),
    .Y(_049_)
  );
  NAND _258_ (
    .A(data_in[5]),
    .B(_071_),
    .Y(_106_)
  );
  NAND _259_ (
    .A(A3[5]),
    .B(_072_),
    .Y(_107_)
  );
  NAND _260_ (
    .A(_106_),
    .B(_107_),
    .Y(_048_)
  );
  NAND _261_ (
    .A(data_in[4]),
    .B(_071_),
    .Y(_108_)
  );
  NAND _262_ (
    .A(A3[4]),
    .B(_072_),
    .Y(_109_)
  );
  NAND _263_ (
    .A(_108_),
    .B(_109_),
    .Y(_047_)
  );
  NAND _264_ (
    .A(data_in[3]),
    .B(_071_),
    .Y(_110_)
  );
  NAND _265_ (
    .A(A3[3]),
    .B(_072_),
    .Y(_111_)
  );
  NAND _266_ (
    .A(_110_),
    .B(_111_),
    .Y(_046_)
  );
  NAND _267_ (
    .A(data_in[2]),
    .B(_071_),
    .Y(_112_)
  );
  NAND _268_ (
    .A(A3[2]),
    .B(_072_),
    .Y(_113_)
  );
  NAND _269_ (
    .A(_112_),
    .B(_113_),
    .Y(_045_)
  );
  NAND _270_ (
    .A(data_in[1]),
    .B(_071_),
    .Y(_114_)
  );
  NAND _271_ (
    .A(A3[1]),
    .B(_072_),
    .Y(_115_)
  );
  NAND _272_ (
    .A(_114_),
    .B(_115_),
    .Y(_044_)
  );
  NAND _273_ (
    .A(data_in[0]),
    .B(_071_),
    .Y(_116_)
  );
  NAND _274_ (
    .A(A3[0]),
    .B(_072_),
    .Y(_117_)
  );
  NAND _275_ (
    .A(_116_),
    .B(_117_),
    .Y(_043_)
  );
  NOR _276_ (
    .A(counter[1]),
    .B(_070_),
    .Y(_118_)
  );
  NAND _277_ (
    .A(_066_),
    .B(_069_),
    .Y(_119_)
  );
  NAND _278_ (
    .A(data_in[7]),
    .B(_118_),
    .Y(_120_)
  );
  NAND _279_ (
    .A(A1[7]),
    .B(_119_),
    .Y(_121_)
  );
  NAND _280_ (
    .A(_120_),
    .B(_121_),
    .Y(_042_)
  );
  NAND _281_ (
    .A(data_in[6]),
    .B(_118_),
    .Y(_122_)
  );
  NAND _282_ (
    .A(A1[6]),
    .B(_119_),
    .Y(_123_)
  );
  NAND _283_ (
    .A(_122_),
    .B(_123_),
    .Y(_041_)
  );
  NAND _284_ (
    .A(data_in[5]),
    .B(_118_),
    .Y(_124_)
  );
  NAND _285_ (
    .A(A1[5]),
    .B(_119_),
    .Y(_125_)
  );
  NAND _286_ (
    .A(_124_),
    .B(_125_),
    .Y(_040_)
  );
  NAND _287_ (
    .A(data_in[4]),
    .B(_118_),
    .Y(_126_)
  );
  NAND _288_ (
    .A(A1[4]),
    .B(_119_),
    .Y(_127_)
  );
  NAND _289_ (
    .A(_126_),
    .B(_127_),
    .Y(_039_)
  );
  NAND _290_ (
    .A(data_in[3]),
    .B(_118_),
    .Y(_128_)
  );
  NAND _291_ (
    .A(A1[3]),
    .B(_119_),
    .Y(_129_)
  );
  NAND _292_ (
    .A(_128_),
    .B(_129_),
    .Y(_038_)
  );
  NAND _293_ (
    .A(data_in[2]),
    .B(_118_),
    .Y(_130_)
  );
  NAND _294_ (
    .A(A1[2]),
    .B(_119_),
    .Y(_131_)
  );
  NAND _295_ (
    .A(_130_),
    .B(_131_),
    .Y(_037_)
  );
  NAND _296_ (
    .A(data_in[1]),
    .B(_118_),
    .Y(_132_)
  );
  NAND _297_ (
    .A(A1[1]),
    .B(_119_),
    .Y(_133_)
  );
  NAND _298_ (
    .A(_132_),
    .B(_133_),
    .Y(_036_)
  );
  NAND _299_ (
    .A(data_in[0]),
    .B(_118_),
    .Y(_134_)
  );
  NAND _300_ (
    .A(A1[0]),
    .B(_119_),
    .Y(_135_)
  );
  NAND _301_ (
    .A(_134_),
    .B(_135_),
    .Y(_035_)
  );
  NAND _302_ (
    .A(A1[7]),
    .B(_078_),
    .Y(_136_)
  );
  NAND _303_ (
    .A(buffer[31]),
    .B(_079_),
    .Y(_137_)
  );
  NAND _304_ (
    .A(_136_),
    .B(_137_),
    .Y(_034_)
  );
  NAND _305_ (
    .A(A1[6]),
    .B(_078_),
    .Y(_138_)
  );
  NAND _306_ (
    .A(buffer[30]),
    .B(_079_),
    .Y(_139_)
  );
  NAND _307_ (
    .A(_138_),
    .B(_139_),
    .Y(_033_)
  );
  NAND _308_ (
    .A(A1[5]),
    .B(_078_),
    .Y(_140_)
  );
  NAND _309_ (
    .A(buffer[29]),
    .B(_079_),
    .Y(_141_)
  );
  NAND _310_ (
    .A(_140_),
    .B(_141_),
    .Y(_032_)
  );
  NAND _311_ (
    .A(A1[4]),
    .B(_078_),
    .Y(_142_)
  );
  NAND _312_ (
    .A(buffer[28]),
    .B(_079_),
    .Y(_143_)
  );
  NAND _313_ (
    .A(_142_),
    .B(_143_),
    .Y(_031_)
  );
  NAND _314_ (
    .A(A1[3]),
    .B(_078_),
    .Y(_144_)
  );
  NAND _315_ (
    .A(buffer[27]),
    .B(_079_),
    .Y(_145_)
  );
  NAND _316_ (
    .A(_144_),
    .B(_145_),
    .Y(_030_)
  );
  NAND _317_ (
    .A(A1[2]),
    .B(_078_),
    .Y(_146_)
  );
  NAND _318_ (
    .A(buffer[26]),
    .B(_079_),
    .Y(_147_)
  );
  NAND _319_ (
    .A(_146_),
    .B(_147_),
    .Y(_029_)
  );
  NAND _320_ (
    .A(A1[1]),
    .B(_078_),
    .Y(_148_)
  );
  NAND _321_ (
    .A(buffer[25]),
    .B(_079_),
    .Y(_149_)
  );
  NAND _322_ (
    .A(_148_),
    .B(_149_),
    .Y(_028_)
  );
  NAND _323_ (
    .A(A1[0]),
    .B(_078_),
    .Y(_150_)
  );
  NAND _324_ (
    .A(buffer[24]),
    .B(_079_),
    .Y(_151_)
  );
  NAND _325_ (
    .A(_150_),
    .B(_151_),
    .Y(_027_)
  );
  NAND _326_ (
    .A(A2[7]),
    .B(_078_),
    .Y(_152_)
  );
  NAND _327_ (
    .A(buffer[23]),
    .B(_079_),
    .Y(_153_)
  );
  NAND _328_ (
    .A(_152_),
    .B(_153_),
    .Y(_026_)
  );
  NAND _329_ (
    .A(A2[6]),
    .B(_078_),
    .Y(_154_)
  );
  NAND _330_ (
    .A(buffer[22]),
    .B(_079_),
    .Y(_155_)
  );
  NAND _331_ (
    .A(_154_),
    .B(_155_),
    .Y(_025_)
  );
  NAND _332_ (
    .A(A2[5]),
    .B(_078_),
    .Y(_156_)
  );
  NAND _333_ (
    .A(buffer[21]),
    .B(_079_),
    .Y(_157_)
  );
  NAND _334_ (
    .A(_156_),
    .B(_157_),
    .Y(_024_)
  );
  NAND _335_ (
    .A(A2[4]),
    .B(_078_),
    .Y(_158_)
  );
  NAND _336_ (
    .A(buffer[20]),
    .B(_079_),
    .Y(_159_)
  );
  NAND _337_ (
    .A(_158_),
    .B(_159_),
    .Y(_023_)
  );
  NAND _338_ (
    .A(A2[3]),
    .B(_078_),
    .Y(_160_)
  );
  NAND _339_ (
    .A(buffer[19]),
    .B(_079_),
    .Y(_161_)
  );
  NAND _340_ (
    .A(_160_),
    .B(_161_),
    .Y(_022_)
  );
  NAND _341_ (
    .A(A2[2]),
    .B(_078_),
    .Y(_162_)
  );
  NAND _342_ (
    .A(buffer[18]),
    .B(_079_),
    .Y(_163_)
  );
  NAND _343_ (
    .A(_162_),
    .B(_163_),
    .Y(_021_)
  );
  NAND _344_ (
    .A(A2[1]),
    .B(_078_),
    .Y(_164_)
  );
  NAND _345_ (
    .A(buffer[17]),
    .B(_079_),
    .Y(_165_)
  );
  NAND _346_ (
    .A(_164_),
    .B(_165_),
    .Y(_020_)
  );
  NAND _347_ (
    .A(A2[0]),
    .B(_078_),
    .Y(_166_)
  );
  NAND _348_ (
    .A(buffer[16]),
    .B(_079_),
    .Y(_167_)
  );
  NAND _349_ (
    .A(_166_),
    .B(_167_),
    .Y(_019_)
  );
  NAND _350_ (
    .A(A3[7]),
    .B(_078_),
    .Y(_168_)
  );
  NAND _351_ (
    .A(buffer[15]),
    .B(_079_),
    .Y(_169_)
  );
  NAND _352_ (
    .A(_168_),
    .B(_169_),
    .Y(_018_)
  );
  NAND _353_ (
    .A(A3[6]),
    .B(_078_),
    .Y(_170_)
  );
  NAND _354_ (
    .A(buffer[14]),
    .B(_079_),
    .Y(_171_)
  );
  NAND _355_ (
    .A(_170_),
    .B(_171_),
    .Y(_017_)
  );
  NAND _356_ (
    .A(A3[5]),
    .B(_078_),
    .Y(_172_)
  );
  NAND _357_ (
    .A(buffer[13]),
    .B(_079_),
    .Y(_173_)
  );
  NAND _358_ (
    .A(_172_),
    .B(_173_),
    .Y(_016_)
  );
  NAND _359_ (
    .A(A3[4]),
    .B(_078_),
    .Y(_174_)
  );
  NAND _360_ (
    .A(buffer[12]),
    .B(_079_),
    .Y(_175_)
  );
  NAND _361_ (
    .A(_174_),
    .B(_175_),
    .Y(_015_)
  );
  NAND _362_ (
    .A(A3[3]),
    .B(_078_),
    .Y(_176_)
  );
  NAND _363_ (
    .A(buffer[11]),
    .B(_079_),
    .Y(_177_)
  );
  NAND _364_ (
    .A(_176_),
    .B(_177_),
    .Y(_014_)
  );
  NAND _365_ (
    .A(A3[2]),
    .B(_078_),
    .Y(_178_)
  );
  NAND _366_ (
    .A(buffer[10]),
    .B(_079_),
    .Y(_179_)
  );
  NAND _367_ (
    .A(_178_),
    .B(_179_),
    .Y(_013_)
  );
  NAND _368_ (
    .A(A3[1]),
    .B(_078_),
    .Y(_180_)
  );
  NAND _369_ (
    .A(buffer[9]),
    .B(_079_),
    .Y(_181_)
  );
  NAND _370_ (
    .A(_180_),
    .B(_181_),
    .Y(_012_)
  );
  NAND _371_ (
    .A(A3[0]),
    .B(_078_),
    .Y(_182_)
  );
  NAND _372_ (
    .A(buffer[8]),
    .B(_079_),
    .Y(_183_)
  );
  NAND _373_ (
    .A(_182_),
    .B(_183_),
    .Y(_011_)
  );
  NAND _374_ (
    .A(data_in[7]),
    .B(_078_),
    .Y(_184_)
  );
  NAND _375_ (
    .A(buffer[7]),
    .B(_079_),
    .Y(_185_)
  );
  NAND _376_ (
    .A(_184_),
    .B(_185_),
    .Y(_010_)
  );
  NAND _377_ (
    .A(data_in[6]),
    .B(_078_),
    .Y(_186_)
  );
  NAND _378_ (
    .A(buffer[6]),
    .B(_079_),
    .Y(_187_)
  );
  NAND _379_ (
    .A(_186_),
    .B(_187_),
    .Y(_009_)
  );
  NAND _380_ (
    .A(data_in[5]),
    .B(_078_),
    .Y(_188_)
  );
  NAND _381_ (
    .A(buffer[5]),
    .B(_079_),
    .Y(_189_)
  );
  NAND _382_ (
    .A(_188_),
    .B(_189_),
    .Y(_008_)
  );
  NAND _383_ (
    .A(data_in[4]),
    .B(_078_),
    .Y(_190_)
  );
  NAND _384_ (
    .A(buffer[4]),
    .B(_079_),
    .Y(_191_)
  );
  NAND _385_ (
    .A(_190_),
    .B(_191_),
    .Y(_007_)
  );
  NAND _386_ (
    .A(data_in[3]),
    .B(_078_),
    .Y(_192_)
  );
  NAND _387_ (
    .A(buffer[3]),
    .B(_079_),
    .Y(_193_)
  );
  NAND _388_ (
    .A(_192_),
    .B(_193_),
    .Y(_006_)
  );
  NAND _389_ (
    .A(data_in[2]),
    .B(_078_),
    .Y(_194_)
  );
  NAND _390_ (
    .A(buffer[2]),
    .B(_079_),
    .Y(_195_)
  );
  NAND _391_ (
    .A(_194_),
    .B(_195_),
    .Y(_005_)
  );
  NAND _392_ (
    .A(data_in[1]),
    .B(_078_),
    .Y(_196_)
  );
  NAND _393_ (
    .A(buffer[1]),
    .B(_079_),
    .Y(_197_)
  );
  NAND _394_ (
    .A(_196_),
    .B(_197_),
    .Y(_004_)
  );
  NAND _395_ (
    .A(data_in[0]),
    .B(_078_),
    .Y(_198_)
  );
  NAND _396_ (
    .A(buffer[0]),
    .B(_079_),
    .Y(_199_)
  );
  NAND _397_ (
    .A(_198_),
    .B(_199_),
    .Y(_003_)
  );
  NOR _398_ (
    .A(counter[2]),
    .B(_067_),
    .Y(_200_)
  );
  NAND _399_ (
    .A(_076_),
    .B(_200_),
    .Y(_062_)
  );
  NOT _400_ (
    .A(clk_4f),
    .Y(_001_)
  );
  NOT _401_ (
    .A(clk_4f),
    .Y(_000_)
  );
  (* src = "Mux8_32_synth.v:80.1-93.4" *)
  DFF _402_ (
    .C(clk_f),
    .D(buffer[0]),
    .Q(data_out[0])
  );
  (* src = "Mux8_32_synth.v:80.1-93.4" *)
  DFF _403_ (
    .C(clk_f),
    .D(buffer[1]),
    .Q(data_out[1])
  );
  (* src = "Mux8_32_synth.v:80.1-93.4" *)
  DFF _404_ (
    .C(clk_f),
    .D(buffer[2]),
    .Q(data_out[2])
  );
  (* src = "Mux8_32_synth.v:80.1-93.4" *)
  DFF _405_ (
    .C(clk_f),
    .D(buffer[3]),
    .Q(data_out[3])
  );
  (* src = "Mux8_32_synth.v:80.1-93.4" *)
  DFF _406_ (
    .C(clk_f),
    .D(buffer[4]),
    .Q(data_out[4])
  );
  (* src = "Mux8_32_synth.v:80.1-93.4" *)
  DFF _407_ (
    .C(clk_f),
    .D(buffer[5]),
    .Q(data_out[5])
  );
  (* src = "Mux8_32_synth.v:80.1-93.4" *)
  DFF _408_ (
    .C(clk_f),
    .D(buffer[6]),
    .Q(data_out[6])
  );
  (* src = "Mux8_32_synth.v:80.1-93.4" *)
  DFF _409_ (
    .C(clk_f),
    .D(buffer[7]),
    .Q(data_out[7])
  );
  (* src = "Mux8_32_synth.v:80.1-93.4" *)
  DFF _410_ (
    .C(clk_f),
    .D(buffer[8]),
    .Q(data_out[8])
  );
  (* src = "Mux8_32_synth.v:80.1-93.4" *)
  DFF _411_ (
    .C(clk_f),
    .D(buffer[9]),
    .Q(data_out[9])
  );
  (* src = "Mux8_32_synth.v:80.1-93.4" *)
  DFF _412_ (
    .C(clk_f),
    .D(buffer[10]),
    .Q(data_out[10])
  );
  (* src = "Mux8_32_synth.v:80.1-93.4" *)
  DFF _413_ (
    .C(clk_f),
    .D(buffer[11]),
    .Q(data_out[11])
  );
  (* src = "Mux8_32_synth.v:80.1-93.4" *)
  DFF _414_ (
    .C(clk_f),
    .D(buffer[12]),
    .Q(data_out[12])
  );
  (* src = "Mux8_32_synth.v:80.1-93.4" *)
  DFF _415_ (
    .C(clk_f),
    .D(buffer[13]),
    .Q(data_out[13])
  );
  (* src = "Mux8_32_synth.v:80.1-93.4" *)
  DFF _416_ (
    .C(clk_f),
    .D(buffer[14]),
    .Q(data_out[14])
  );
  (* src = "Mux8_32_synth.v:80.1-93.4" *)
  DFF _417_ (
    .C(clk_f),
    .D(buffer[15]),
    .Q(data_out[15])
  );
  (* src = "Mux8_32_synth.v:80.1-93.4" *)
  DFF _418_ (
    .C(clk_f),
    .D(buffer[16]),
    .Q(data_out[16])
  );
  (* src = "Mux8_32_synth.v:80.1-93.4" *)
  DFF _419_ (
    .C(clk_f),
    .D(buffer[17]),
    .Q(data_out[17])
  );
  (* src = "Mux8_32_synth.v:80.1-93.4" *)
  DFF _420_ (
    .C(clk_f),
    .D(buffer[18]),
    .Q(data_out[18])
  );
  (* src = "Mux8_32_synth.v:80.1-93.4" *)
  DFF _421_ (
    .C(clk_f),
    .D(buffer[19]),
    .Q(data_out[19])
  );
  (* src = "Mux8_32_synth.v:80.1-93.4" *)
  DFF _422_ (
    .C(clk_f),
    .D(buffer[20]),
    .Q(data_out[20])
  );
  (* src = "Mux8_32_synth.v:80.1-93.4" *)
  DFF _423_ (
    .C(clk_f),
    .D(buffer[21]),
    .Q(data_out[21])
  );
  (* src = "Mux8_32_synth.v:80.1-93.4" *)
  DFF _424_ (
    .C(clk_f),
    .D(buffer[22]),
    .Q(data_out[22])
  );
  (* src = "Mux8_32_synth.v:80.1-93.4" *)
  DFF _425_ (
    .C(clk_f),
    .D(buffer[23]),
    .Q(data_out[23])
  );
  (* src = "Mux8_32_synth.v:80.1-93.4" *)
  DFF _426_ (
    .C(clk_f),
    .D(buffer[24]),
    .Q(data_out[24])
  );
  (* src = "Mux8_32_synth.v:80.1-93.4" *)
  DFF _427_ (
    .C(clk_f),
    .D(buffer[25]),
    .Q(data_out[25])
  );
  (* src = "Mux8_32_synth.v:80.1-93.4" *)
  DFF _428_ (
    .C(clk_f),
    .D(buffer[26]),
    .Q(data_out[26])
  );
  (* src = "Mux8_32_synth.v:80.1-93.4" *)
  DFF _429_ (
    .C(clk_f),
    .D(buffer[27]),
    .Q(data_out[27])
  );
  (* src = "Mux8_32_synth.v:80.1-93.4" *)
  DFF _430_ (
    .C(clk_f),
    .D(buffer[28]),
    .Q(data_out[28])
  );
  (* src = "Mux8_32_synth.v:80.1-93.4" *)
  DFF _431_ (
    .C(clk_f),
    .D(buffer[29]),
    .Q(data_out[29])
  );
  (* src = "Mux8_32_synth.v:80.1-93.4" *)
  DFF _432_ (
    .C(clk_f),
    .D(buffer[30]),
    .Q(data_out[30])
  );
  (* src = "Mux8_32_synth.v:80.1-93.4" *)
  DFF _433_ (
    .C(clk_f),
    .D(buffer[31]),
    .Q(data_out[31])
  );
  (* src = "Mux8_32_synth.v:41.1-58.4" *)
  DFF _434_ (
    .C(clk_4f),
    .D(_003_),
    .Q(buffer[0])
  );
  (* src = "Mux8_32_synth.v:41.1-58.4" *)
  DFF _435_ (
    .C(clk_4f),
    .D(_004_),
    .Q(buffer[1])
  );
  (* src = "Mux8_32_synth.v:41.1-58.4" *)
  DFF _436_ (
    .C(clk_4f),
    .D(_005_),
    .Q(buffer[2])
  );
  (* src = "Mux8_32_synth.v:41.1-58.4" *)
  DFF _437_ (
    .C(clk_4f),
    .D(_006_),
    .Q(buffer[3])
  );
  (* src = "Mux8_32_synth.v:41.1-58.4" *)
  DFF _438_ (
    .C(clk_4f),
    .D(_007_),
    .Q(buffer[4])
  );
  (* src = "Mux8_32_synth.v:41.1-58.4" *)
  DFF _439_ (
    .C(clk_4f),
    .D(_008_),
    .Q(buffer[5])
  );
  (* src = "Mux8_32_synth.v:41.1-58.4" *)
  DFF _440_ (
    .C(clk_4f),
    .D(_009_),
    .Q(buffer[6])
  );
  (* src = "Mux8_32_synth.v:41.1-58.4" *)
  DFF _441_ (
    .C(clk_4f),
    .D(_010_),
    .Q(buffer[7])
  );
  (* src = "Mux8_32_synth.v:41.1-58.4" *)
  DFF _442_ (
    .C(clk_4f),
    .D(_011_),
    .Q(buffer[8])
  );
  (* src = "Mux8_32_synth.v:41.1-58.4" *)
  DFF _443_ (
    .C(clk_4f),
    .D(_012_),
    .Q(buffer[9])
  );
  (* src = "Mux8_32_synth.v:41.1-58.4" *)
  DFF _444_ (
    .C(clk_4f),
    .D(_013_),
    .Q(buffer[10])
  );
  (* src = "Mux8_32_synth.v:41.1-58.4" *)
  DFF _445_ (
    .C(clk_4f),
    .D(_014_),
    .Q(buffer[11])
  );
  (* src = "Mux8_32_synth.v:41.1-58.4" *)
  DFF _446_ (
    .C(clk_4f),
    .D(_015_),
    .Q(buffer[12])
  );
  (* src = "Mux8_32_synth.v:41.1-58.4" *)
  DFF _447_ (
    .C(clk_4f),
    .D(_016_),
    .Q(buffer[13])
  );
  (* src = "Mux8_32_synth.v:41.1-58.4" *)
  DFF _448_ (
    .C(clk_4f),
    .D(_017_),
    .Q(buffer[14])
  );
  (* src = "Mux8_32_synth.v:41.1-58.4" *)
  DFF _449_ (
    .C(clk_4f),
    .D(_018_),
    .Q(buffer[15])
  );
  (* src = "Mux8_32_synth.v:41.1-58.4" *)
  DFF _450_ (
    .C(clk_4f),
    .D(_019_),
    .Q(buffer[16])
  );
  (* src = "Mux8_32_synth.v:41.1-58.4" *)
  DFF _451_ (
    .C(clk_4f),
    .D(_020_),
    .Q(buffer[17])
  );
  (* src = "Mux8_32_synth.v:41.1-58.4" *)
  DFF _452_ (
    .C(clk_4f),
    .D(_021_),
    .Q(buffer[18])
  );
  (* src = "Mux8_32_synth.v:41.1-58.4" *)
  DFF _453_ (
    .C(clk_4f),
    .D(_022_),
    .Q(buffer[19])
  );
  (* src = "Mux8_32_synth.v:41.1-58.4" *)
  DFF _454_ (
    .C(clk_4f),
    .D(_023_),
    .Q(buffer[20])
  );
  (* src = "Mux8_32_synth.v:41.1-58.4" *)
  DFF _455_ (
    .C(clk_4f),
    .D(_024_),
    .Q(buffer[21])
  );
  (* src = "Mux8_32_synth.v:41.1-58.4" *)
  DFF _456_ (
    .C(clk_4f),
    .D(_025_),
    .Q(buffer[22])
  );
  (* src = "Mux8_32_synth.v:41.1-58.4" *)
  DFF _457_ (
    .C(clk_4f),
    .D(_026_),
    .Q(buffer[23])
  );
  (* src = "Mux8_32_synth.v:41.1-58.4" *)
  DFF _458_ (
    .C(clk_4f),
    .D(_027_),
    .Q(buffer[24])
  );
  (* src = "Mux8_32_synth.v:41.1-58.4" *)
  DFF _459_ (
    .C(clk_4f),
    .D(_028_),
    .Q(buffer[25])
  );
  (* src = "Mux8_32_synth.v:41.1-58.4" *)
  DFF _460_ (
    .C(clk_4f),
    .D(_029_),
    .Q(buffer[26])
  );
  (* src = "Mux8_32_synth.v:41.1-58.4" *)
  DFF _461_ (
    .C(clk_4f),
    .D(_030_),
    .Q(buffer[27])
  );
  (* src = "Mux8_32_synth.v:41.1-58.4" *)
  DFF _462_ (
    .C(clk_4f),
    .D(_031_),
    .Q(buffer[28])
  );
  (* src = "Mux8_32_synth.v:41.1-58.4" *)
  DFF _463_ (
    .C(clk_4f),
    .D(_032_),
    .Q(buffer[29])
  );
  (* src = "Mux8_32_synth.v:41.1-58.4" *)
  DFF _464_ (
    .C(clk_4f),
    .D(_033_),
    .Q(buffer[30])
  );
  (* src = "Mux8_32_synth.v:41.1-58.4" *)
  DFF _465_ (
    .C(clk_4f),
    .D(_034_),
    .Q(buffer[31])
  );
  (* src = "Mux8_32_synth.v:41.1-58.4" *)
  DFF _466_ (
    .C(clk_4f),
    .D(_035_),
    .Q(A1[0])
  );
  (* src = "Mux8_32_synth.v:41.1-58.4" *)
  DFF _467_ (
    .C(clk_4f),
    .D(_036_),
    .Q(A1[1])
  );
  (* src = "Mux8_32_synth.v:41.1-58.4" *)
  DFF _468_ (
    .C(clk_4f),
    .D(_037_),
    .Q(A1[2])
  );
  (* src = "Mux8_32_synth.v:41.1-58.4" *)
  DFF _469_ (
    .C(clk_4f),
    .D(_038_),
    .Q(A1[3])
  );
  (* src = "Mux8_32_synth.v:41.1-58.4" *)
  DFF _470_ (
    .C(clk_4f),
    .D(_039_),
    .Q(A1[4])
  );
  (* src = "Mux8_32_synth.v:41.1-58.4" *)
  DFF _471_ (
    .C(clk_4f),
    .D(_040_),
    .Q(A1[5])
  );
  (* src = "Mux8_32_synth.v:41.1-58.4" *)
  DFF _472_ (
    .C(clk_4f),
    .D(_041_),
    .Q(A1[6])
  );
  (* src = "Mux8_32_synth.v:41.1-58.4" *)
  DFF _473_ (
    .C(clk_4f),
    .D(_042_),
    .Q(A1[7])
  );
  (* src = "Mux8_32_synth.v:41.1-58.4" *)
  DFF _474_ (
    .C(clk_4f),
    .D(_043_),
    .Q(A3[0])
  );
  (* src = "Mux8_32_synth.v:41.1-58.4" *)
  DFF _475_ (
    .C(clk_4f),
    .D(_044_),
    .Q(A3[1])
  );
  (* src = "Mux8_32_synth.v:41.1-58.4" *)
  DFF _476_ (
    .C(clk_4f),
    .D(_045_),
    .Q(A3[2])
  );
  (* src = "Mux8_32_synth.v:41.1-58.4" *)
  DFF _477_ (
    .C(clk_4f),
    .D(_046_),
    .Q(A3[3])
  );
  (* src = "Mux8_32_synth.v:41.1-58.4" *)
  DFF _478_ (
    .C(clk_4f),
    .D(_047_),
    .Q(A3[4])
  );
  (* src = "Mux8_32_synth.v:41.1-58.4" *)
  DFF _479_ (
    .C(clk_4f),
    .D(_048_),
    .Q(A3[5])
  );
  (* src = "Mux8_32_synth.v:41.1-58.4" *)
  DFF _480_ (
    .C(clk_4f),
    .D(_049_),
    .Q(A3[6])
  );
  (* src = "Mux8_32_synth.v:41.1-58.4" *)
  DFF _481_ (
    .C(clk_4f),
    .D(_050_),
    .Q(A3[7])
  );
  (* src = "Mux8_32_synth.v:41.1-58.4" *)
  DFF _482_ (
    .C(clk_4f),
    .D(_051_),
    .Q(A2[0])
  );
  (* src = "Mux8_32_synth.v:41.1-58.4" *)
  DFF _483_ (
    .C(clk_4f),
    .D(_052_),
    .Q(A2[1])
  );
  (* src = "Mux8_32_synth.v:41.1-58.4" *)
  DFF _484_ (
    .C(clk_4f),
    .D(_053_),
    .Q(A2[2])
  );
  (* src = "Mux8_32_synth.v:41.1-58.4" *)
  DFF _485_ (
    .C(clk_4f),
    .D(_054_),
    .Q(A2[3])
  );
  (* src = "Mux8_32_synth.v:41.1-58.4" *)
  DFF _486_ (
    .C(clk_4f),
    .D(_055_),
    .Q(A2[4])
  );
  (* src = "Mux8_32_synth.v:41.1-58.4" *)
  DFF _487_ (
    .C(clk_4f),
    .D(_056_),
    .Q(A2[5])
  );
  (* src = "Mux8_32_synth.v:41.1-58.4" *)
  DFF _488_ (
    .C(clk_4f),
    .D(_057_),
    .Q(A2[6])
  );
  (* src = "Mux8_32_synth.v:41.1-58.4" *)
  DFF _489_ (
    .C(clk_4f),
    .D(_058_),
    .Q(A2[7])
  );
  (* src = "Mux8_32_synth.v:19.1-29.4" *)
  DFF _490_ (
    .C(_000_),
    .D(_059_),
    .Q(counter[1])
  );
  (* src = "Mux8_32_synth.v:19.1-29.4" *)
  DFF _491_ (
    .C(_001_),
    .D(_060_),
    .Q(counter[2])
  );
  (* src = "Mux8_32_synth.v:19.1-29.4" *)
  DFF _492_ (
    .C(_002_),
    .D(_061_),
    .Q(counter[0])
  );
  (* src = "Mux8_32_synth.v:80.1-93.4" *)
  DFF _493_ (
    .C(clk_f),
    .D(_062_),
    .Q(flag2)
  );
  assign flag = 1'h1;
  assign valid_out = flag2;
endmodule
