/* Generated by Yosys 0.9+3565 (git sha1 474cd02e, gcc 9.3.0-10ubuntu2 -fPIC -Os) */

(* top =  1  *)
(* src = "Serial_Paralelo_synth.v:1.1-83.10" *)
module Serial_Paralelo_synth(clk_4f, clk_32f, data_in, reset, data_out, valid_out, active);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  (* src = "Serial_Paralelo_synth.v:8.16-8.22" *)
  output active;
  (* src = "Serial_Paralelo_synth.v:11.11-11.17" *)
  wire [7:0] buffer;
  (* src = "Serial_Paralelo_synth.v:3.11-3.18" *)
  input clk_32f;
  (* src = "Serial_Paralelo_synth.v:2.11-2.17" *)
  input clk_4f;
  (* src = "Serial_Paralelo_synth.v:12.10-12.21" *)
  wire [2:0] contador_BC;
  (* src = "Serial_Paralelo_synth.v:13.10-13.21" *)
  wire [3:0] counter_out;
  (* src = "Serial_Paralelo_synth.v:4.11-4.18" *)
  input data_in;
  (* src = "Serial_Paralelo_synth.v:6.22-6.30" *)
  output [7:0] data_out;
  (* src = "Serial_Paralelo_synth.v:5.11-5.16" *)
  input reset;
  (* src = "Serial_Paralelo_synth.v:7.16-7.25" *)
  output valid_out;
  NOT _124_ (
    .A(reset),
    .Y(_090_)
  );
  NOT _125_ (
    .A(contador_BC[0]),
    .Y(_091_)
  );
  NOT _126_ (
    .A(active),
    .Y(_092_)
  );
  NOT _127_ (
    .A(clk_32f),
    .Y(_007_)
  );
  NOT _128_ (
    .A(buffer[6]),
    .Y(_093_)
  );
  NOT _129_ (
    .A(buffer[5]),
    .Y(_094_)
  );
  NOT _130_ (
    .A(buffer[4]),
    .Y(_095_)
  );
  NOT _131_ (
    .A(buffer[3]),
    .Y(_096_)
  );
  NOT _132_ (
    .A(buffer[2]),
    .Y(_097_)
  );
  NOT _133_ (
    .A(buffer[1]),
    .Y(_098_)
  );
  NOT _134_ (
    .A(buffer[0]),
    .Y(_099_)
  );
  NOT _135_ (
    .A(counter_out[0]),
    .Y(_100_)
  );
  NOT _136_ (
    .A(counter_out[1]),
    .Y(_101_)
  );
  NOR _137_ (
    .A(counter_out[0]),
    .B(counter_out[1]),
    .Y(_102_)
  );
  NAND _138_ (
    .A(counter_out[3]),
    .B(_102_),
    .Y(_103_)
  );
  NOR _139_ (
    .A(counter_out[2]),
    .B(_103_),
    .Y(_104_)
  );
  NOT _140_ (
    .A(_104_),
    .Y(_105_)
  );
  NOR _141_ (
    .A(_092_),
    .B(_105_),
    .Y(_106_)
  );
  NAND _142_ (
    .A(active),
    .B(_104_),
    .Y(_107_)
  );
  NAND _143_ (
    .A(buffer[2]),
    .B(_098_),
    .Y(_108_)
  );
  NAND _144_ (
    .A(_099_),
    .B(buffer[7]),
    .Y(_109_)
  );
  NOR _145_ (
    .A(_108_),
    .B(_109_),
    .Y(_110_)
  );
  NAND _146_ (
    .A(_093_),
    .B(buffer[5]),
    .Y(_111_)
  );
  NAND _147_ (
    .A(buffer[4]),
    .B(buffer[3]),
    .Y(_112_)
  );
  NOR _148_ (
    .A(_111_),
    .B(_112_),
    .Y(_113_)
  );
  NAND _149_ (
    .A(_110_),
    .B(_113_),
    .Y(_114_)
  );
  NOT _150_ (
    .A(_114_),
    .Y(_115_)
  );
  NOR _151_ (
    .A(_107_),
    .B(_115_),
    .Y(_116_)
  );
  NAND _152_ (
    .A(reset),
    .B(_116_),
    .Y(_117_)
  );
  NOT _153_ (
    .A(_117_),
    .Y(_118_)
  );
  NAND _154_ (
    .A(buffer[7]),
    .B(_118_),
    .Y(_119_)
  );
  NOR _155_ (
    .A(_090_),
    .B(_106_),
    .Y(_120_)
  );
  NAND _156_ (
    .A(data_out[7]),
    .B(_120_),
    .Y(_121_)
  );
  NAND _157_ (
    .A(_119_),
    .B(_121_),
    .Y(_031_)
  );
  NOR _158_ (
    .A(data_out[6]),
    .B(_106_),
    .Y(_122_)
  );
  NOR _159_ (
    .A(_090_),
    .B(_093_),
    .Y(_018_)
  );
  NOR _160_ (
    .A(_120_),
    .B(_018_),
    .Y(_123_)
  );
  NOR _161_ (
    .A(_122_),
    .B(_123_),
    .Y(_030_)
  );
  NAND _162_ (
    .A(data_out[5]),
    .B(_120_),
    .Y(_033_)
  );
  NOR _163_ (
    .A(_090_),
    .B(_094_),
    .Y(_017_)
  );
  NAND _164_ (
    .A(_116_),
    .B(_017_),
    .Y(_034_)
  );
  NAND _165_ (
    .A(_033_),
    .B(_034_),
    .Y(_029_)
  );
  NAND _166_ (
    .A(data_out[4]),
    .B(_120_),
    .Y(_035_)
  );
  NOR _167_ (
    .A(_090_),
    .B(_095_),
    .Y(_016_)
  );
  NAND _168_ (
    .A(_116_),
    .B(_016_),
    .Y(_036_)
  );
  NAND _169_ (
    .A(_035_),
    .B(_036_),
    .Y(_028_)
  );
  NAND _170_ (
    .A(data_out[3]),
    .B(_120_),
    .Y(_037_)
  );
  NOR _171_ (
    .A(_090_),
    .B(_096_),
    .Y(_015_)
  );
  NAND _172_ (
    .A(_116_),
    .B(_015_),
    .Y(_038_)
  );
  NAND _173_ (
    .A(_037_),
    .B(_038_),
    .Y(_027_)
  );
  NAND _174_ (
    .A(data_out[2]),
    .B(_120_),
    .Y(_039_)
  );
  NOR _175_ (
    .A(_090_),
    .B(_097_),
    .Y(_014_)
  );
  NAND _176_ (
    .A(_116_),
    .B(_014_),
    .Y(_040_)
  );
  NAND _177_ (
    .A(_039_),
    .B(_040_),
    .Y(_026_)
  );
  NOR _178_ (
    .A(data_out[1]),
    .B(_106_),
    .Y(_041_)
  );
  NOR _179_ (
    .A(_090_),
    .B(_098_),
    .Y(_013_)
  );
  NOR _180_ (
    .A(_120_),
    .B(_013_),
    .Y(_042_)
  );
  NOR _181_ (
    .A(_041_),
    .B(_042_),
    .Y(_025_)
  );
  NOR _182_ (
    .A(data_out[0]),
    .B(_106_),
    .Y(_043_)
  );
  NOR _183_ (
    .A(_090_),
    .B(_099_),
    .Y(_012_)
  );
  NOR _184_ (
    .A(_120_),
    .B(_012_),
    .Y(_044_)
  );
  NOR _185_ (
    .A(_043_),
    .B(_044_),
    .Y(_024_)
  );
  NOR _186_ (
    .A(contador_BC[1]),
    .B(contador_BC[0]),
    .Y(_045_)
  );
  NAND _187_ (
    .A(contador_BC[2]),
    .B(_045_),
    .Y(_046_)
  );
  NAND _188_ (
    .A(_092_),
    .B(_046_),
    .Y(_047_)
  );
  NOT _189_ (
    .A(_047_),
    .Y(_048_)
  );
  NOR _190_ (
    .A(_115_),
    .B(_047_),
    .Y(_049_)
  );
  NAND _191_ (
    .A(_114_),
    .B(_048_),
    .Y(_050_)
  );
  NOR _192_ (
    .A(_105_),
    .B(_049_),
    .Y(_051_)
  );
  NAND _193_ (
    .A(_104_),
    .B(_050_),
    .Y(_052_)
  );
  NAND _194_ (
    .A(contador_BC[1]),
    .B(contador_BC[0]),
    .Y(_053_)
  );
  NOT _195_ (
    .A(_053_),
    .Y(_054_)
  );
  NOR _196_ (
    .A(_052_),
    .B(_053_),
    .Y(_055_)
  );
  NOR _197_ (
    .A(contador_BC[2]),
    .B(_055_),
    .Y(_056_)
  );
  NOR _198_ (
    .A(active),
    .B(_114_),
    .Y(_057_)
  );
  NOT _199_ (
    .A(_057_),
    .Y(_058_)
  );
  NOR _200_ (
    .A(_052_),
    .B(_057_),
    .Y(_059_)
  );
  NAND _201_ (
    .A(_051_),
    .B(_058_),
    .Y(_060_)
  );
  NOR _202_ (
    .A(_090_),
    .B(_059_),
    .Y(_061_)
  );
  NAND _203_ (
    .A(reset),
    .B(_060_),
    .Y(_062_)
  );
  NAND _204_ (
    .A(contador_BC[2]),
    .B(_055_),
    .Y(_063_)
  );
  NAND _205_ (
    .A(_061_),
    .B(_063_),
    .Y(_064_)
  );
  NOR _206_ (
    .A(_056_),
    .B(_064_),
    .Y(_023_)
  );
  NOR _207_ (
    .A(contador_BC[1]),
    .B(_051_),
    .Y(_065_)
  );
  NOR _208_ (
    .A(_045_),
    .B(_054_),
    .Y(_066_)
  );
  NAND _209_ (
    .A(_057_),
    .B(_066_),
    .Y(_067_)
  );
  NAND _210_ (
    .A(_051_),
    .B(_067_),
    .Y(_068_)
  );
  NAND _211_ (
    .A(reset),
    .B(_068_),
    .Y(_069_)
  );
  NOR _212_ (
    .A(_065_),
    .B(_069_),
    .Y(_022_)
  );
  NOR _213_ (
    .A(_091_),
    .B(_051_),
    .Y(_070_)
  );
  NOR _214_ (
    .A(contador_BC[0]),
    .B(_052_),
    .Y(_071_)
  );
  NOR _215_ (
    .A(_070_),
    .B(_071_),
    .Y(_072_)
  );
  NOR _216_ (
    .A(_062_),
    .B(_072_),
    .Y(_021_)
  );
  NOR _217_ (
    .A(active),
    .B(_104_),
    .Y(_073_)
  );
  NAND _218_ (
    .A(reset),
    .B(_047_),
    .Y(_074_)
  );
  NOR _219_ (
    .A(_073_),
    .B(_074_),
    .Y(_020_)
  );
  NOR _220_ (
    .A(_090_),
    .B(counter_out[0]),
    .Y(_019_)
  );
  NAND _221_ (
    .A(reset),
    .B(data_in),
    .Y(_075_)
  );
  NOT _222_ (
    .A(_075_),
    .Y(_011_)
  );
  NOR _223_ (
    .A(_100_),
    .B(_101_),
    .Y(_076_)
  );
  NAND _224_ (
    .A(counter_out[0]),
    .B(counter_out[1]),
    .Y(_077_)
  );
  NAND _225_ (
    .A(counter_out[2]),
    .B(_076_),
    .Y(_078_)
  );
  NOT _226_ (
    .A(_078_),
    .Y(_079_)
  );
  NOR _227_ (
    .A(counter_out[3]),
    .B(_079_),
    .Y(_080_)
  );
  NOR _228_ (
    .A(_090_),
    .B(_104_),
    .Y(_081_)
  );
  NAND _229_ (
    .A(reset),
    .B(_078_),
    .Y(_082_)
  );
  NOR _230_ (
    .A(_104_),
    .B(_082_),
    .Y(_083_)
  );
  NAND _231_ (
    .A(_078_),
    .B(_081_),
    .Y(_084_)
  );
  NOR _232_ (
    .A(_090_),
    .B(counter_out[3]),
    .Y(_085_)
  );
  NOR _233_ (
    .A(_083_),
    .B(_085_),
    .Y(_086_)
  );
  NOR _234_ (
    .A(_080_),
    .B(_086_),
    .Y(_010_)
  );
  NOR _235_ (
    .A(counter_out[2]),
    .B(_076_),
    .Y(_087_)
  );
  NOR _236_ (
    .A(_084_),
    .B(_087_),
    .Y(_009_)
  );
  NAND _237_ (
    .A(reset),
    .B(_077_),
    .Y(_088_)
  );
  NOR _238_ (
    .A(_102_),
    .B(_088_),
    .Y(_008_)
  );
  NAND _239_ (
    .A(valid_out),
    .B(_120_),
    .Y(_089_)
  );
  NAND _240_ (
    .A(_117_),
    .B(_089_),
    .Y(_032_)
  );
  NOT _241_ (
    .A(clk_32f),
    .Y(_006_)
  );
  NOT _242_ (
    .A(clk_32f),
    .Y(_005_)
  );
  NOT _243_ (
    .A(clk_32f),
    .Y(_004_)
  );
  NOT _244_ (
    .A(clk_32f),
    .Y(_003_)
  );
  NOT _245_ (
    .A(clk_32f),
    .Y(_002_)
  );
  NOT _246_ (
    .A(clk_32f),
    .Y(_001_)
  );
  NOT _247_ (
    .A(clk_32f),
    .Y(_000_)
  );
  (* src = "Serial_Paralelo_synth.v:40.1-81.4" *)
  DFF _248_ (
    .C(clk_32f),
    .D(_008_),
    .Q(counter_out[1])
  );
  (* src = "Serial_Paralelo_synth.v:40.1-81.4" *)
  DFF _249_ (
    .C(clk_32f),
    .D(_009_),
    .Q(counter_out[2])
  );
  (* src = "Serial_Paralelo_synth.v:40.1-81.4" *)
  DFF _250_ (
    .C(clk_32f),
    .D(_010_),
    .Q(counter_out[3])
  );
  (* src = "Serial_Paralelo_synth.v:21.1-36.4" *)
  DFF _251_ (
    .C(_000_),
    .D(_011_),
    .Q(buffer[0])
  );
  (* src = "Serial_Paralelo_synth.v:21.1-36.4" *)
  DFF _252_ (
    .C(_001_),
    .D(_012_),
    .Q(buffer[1])
  );
  (* src = "Serial_Paralelo_synth.v:21.1-36.4" *)
  DFF _253_ (
    .C(_002_),
    .D(_013_),
    .Q(buffer[2])
  );
  (* src = "Serial_Paralelo_synth.v:21.1-36.4" *)
  DFF _254_ (
    .C(_003_),
    .D(_014_),
    .Q(buffer[3])
  );
  (* src = "Serial_Paralelo_synth.v:21.1-36.4" *)
  DFF _255_ (
    .C(_004_),
    .D(_015_),
    .Q(buffer[4])
  );
  (* src = "Serial_Paralelo_synth.v:21.1-36.4" *)
  DFF _256_ (
    .C(_005_),
    .D(_016_),
    .Q(buffer[5])
  );
  (* src = "Serial_Paralelo_synth.v:21.1-36.4" *)
  DFF _257_ (
    .C(_006_),
    .D(_017_),
    .Q(buffer[6])
  );
  (* src = "Serial_Paralelo_synth.v:21.1-36.4" *)
  DFF _258_ (
    .C(_007_),
    .D(_018_),
    .Q(buffer[7])
  );
  (* src = "Serial_Paralelo_synth.v:40.1-81.4" *)
  DFF _259_ (
    .C(clk_32f),
    .D(_019_),
    .Q(counter_out[0])
  );
  (* src = "Serial_Paralelo_synth.v:40.1-81.4" *)
  DFF _260_ (
    .C(clk_32f),
    .D(_020_),
    .Q(active)
  );
  (* src = "Serial_Paralelo_synth.v:40.1-81.4" *)
  DFF _261_ (
    .C(clk_32f),
    .D(_021_),
    .Q(contador_BC[0])
  );
  (* src = "Serial_Paralelo_synth.v:40.1-81.4" *)
  DFF _262_ (
    .C(clk_32f),
    .D(_022_),
    .Q(contador_BC[1])
  );
  (* src = "Serial_Paralelo_synth.v:40.1-81.4" *)
  DFF _263_ (
    .C(clk_32f),
    .D(_023_),
    .Q(contador_BC[2])
  );
  (* src = "Serial_Paralelo_synth.v:40.1-81.4" *)
  DFF _264_ (
    .C(clk_32f),
    .D(_024_),
    .Q(data_out[0])
  );
  (* src = "Serial_Paralelo_synth.v:40.1-81.4" *)
  DFF _265_ (
    .C(clk_32f),
    .D(_025_),
    .Q(data_out[1])
  );
  (* src = "Serial_Paralelo_synth.v:40.1-81.4" *)
  DFF _266_ (
    .C(clk_32f),
    .D(_026_),
    .Q(data_out[2])
  );
  (* src = "Serial_Paralelo_synth.v:40.1-81.4" *)
  DFF _267_ (
    .C(clk_32f),
    .D(_027_),
    .Q(data_out[3])
  );
  (* src = "Serial_Paralelo_synth.v:40.1-81.4" *)
  DFF _268_ (
    .C(clk_32f),
    .D(_028_),
    .Q(data_out[4])
  );
  (* src = "Serial_Paralelo_synth.v:40.1-81.4" *)
  DFF _269_ (
    .C(clk_32f),
    .D(_029_),
    .Q(data_out[5])
  );
  (* src = "Serial_Paralelo_synth.v:40.1-81.4" *)
  DFF _270_ (
    .C(clk_32f),
    .D(_030_),
    .Q(data_out[6])
  );
  (* src = "Serial_Paralelo_synth.v:40.1-81.4" *)
  DFF _271_ (
    .C(clk_32f),
    .D(_031_),
    .Q(data_out[7])
  );
  (* src = "Serial_Paralelo_synth.v:40.1-81.4" *)
  DFF _272_ (
    .C(clk_32f),
    .D(_032_),
    .Q(valid_out)
  );
endmodule
